/*
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FlowServiceAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/webmethods/flow/parser/antlr/internal/InternalFlowService.tokens");
	}
}
