/*
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.parser.antlr;

import com.google.inject.Inject;
import com.webmethods.flow.parser.antlr.internal.InternalFlowServiceParser;
import com.webmethods.flow.services.FlowServiceGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FlowServiceParser extends AbstractAntlrParser {

	@Inject
	private FlowServiceGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFlowServiceParser createParser(XtextTokenStream stream) {
		return new InternalFlowServiceParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public FlowServiceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FlowServiceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
