/*
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FlowServiceRuntimeModule extends AbstractFlowServiceRuntimeModule {
}
