/*
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FlowServiceStandaloneSetup extends FlowServiceStandaloneSetupGenerated {

	public static void doSetup() {
		new FlowServiceStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
