/*
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.ui.tests;

import com.google.inject.Injector;
import com.webmethods.flow.ui.internal.FlowActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class FlowServiceUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FlowActivator.getInstance().getInjector("com.webmethods.flow.FlowService");
	}

}
