/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Branch Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.BranchProperty#getSwitch <em>Switch</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.BranchProperty#getEval <em>Eval</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getBranchProperty()
 * @model
 * @generated
 */
public interface BranchProperty extends EObject
{
  /**
   * Returns the value of the '<em><b>Switch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Switch</em>' attribute.
   * @see #setSwitch(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getBranchProperty_Switch()
   * @model
   * @generated
   */
  String getSwitch();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.BranchProperty#getSwitch <em>Switch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Switch</em>' attribute.
   * @see #getSwitch()
   * @generated
   */
  void setSwitch(String value);

  /**
   * Returns the value of the '<em><b>Eval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eval</em>' attribute.
   * @see #setEval(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getBranchProperty_Eval()
   * @model
   * @generated
   */
  String getEval();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.BranchProperty#getEval <em>Eval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eval</em>' attribute.
   * @see #getEval()
   * @generated
   */
  void setEval(String value);

} // BranchProperty
