/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Branch Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.BranchStep#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.BranchStep#getBranchProps <em>Branch Props</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.BranchStep#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getBranchStep()
 * @model
 * @generated
 */
public interface BranchStep extends Step
{
  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.StepProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getBranchStep_Properties()
   * @model containment="true"
   * @generated
   */
  EList<StepProperty> getProperties();

  /**
   * Returns the value of the '<em><b>Branch Props</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.BranchProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Branch Props</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getBranchStep_BranchProps()
   * @model containment="true"
   * @generated
   */
  EList<BranchProperty> getBranchProps();

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.Step}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getBranchStep_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

} // BranchStep
