/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Catch Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.CatchProperty#getExit <em>Exit</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.CatchProperty#getFailures <em>Failures</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.CatchProperty#getSelection <em>Selection</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getCatchProperty()
 * @model
 * @generated
 */
public interface CatchProperty extends EObject
{
  /**
   * Returns the value of the '<em><b>Exit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exit</em>' attribute.
   * @see #setExit(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getCatchProperty_Exit()
   * @model
   * @generated
   */
  String getExit();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.CatchProperty#getExit <em>Exit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exit</em>' attribute.
   * @see #getExit()
   * @generated
   */
  void setExit(String value);

  /**
   * Returns the value of the '<em><b>Failures</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Failures</em>' attribute.
   * @see #setFailures(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getCatchProperty_Failures()
   * @model
   * @generated
   */
  String getFailures();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.CatchProperty#getFailures <em>Failures</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Failures</em>' attribute.
   * @see #getFailures()
   * @generated
   */
  void setFailures(String value);

  /**
   * Returns the value of the '<em><b>Selection</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selection</em>' attribute.
   * @see #setSelection(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getCatchProperty_Selection()
   * @model
   * @generated
   */
  String getSelection();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.CatchProperty#getSelection <em>Selection</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selection</em>' attribute.
   * @see #getSelection()
   * @generated
   */
  void setSelection(String value);

} // CatchProperty
