/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Catch Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.CatchStep#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.CatchStep#getCatchProps <em>Catch Props</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.CatchStep#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getCatchStep()
 * @model
 * @generated
 */
public interface CatchStep extends EObject
{
  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.StepProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getCatchStep_Properties()
   * @model containment="true"
   * @generated
   */
  EList<StepProperty> getProperties();

  /**
   * Returns the value of the '<em><b>Catch Props</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.CatchProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Catch Props</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getCatchStep_CatchProps()
   * @model containment="true"
   * @generated
   */
  EList<CatchProperty> getCatchProps();

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.Step}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getCatchStep_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

} // CatchStep
