/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exit Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.ExitProperty#getComment <em>Comment</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.ExitProperty#getLabel <em>Label</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.ExitProperty#getSignal <em>Signal</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.ExitProperty#getFailureName <em>Failure Name</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.ExitProperty#getFailureInstance <em>Failure Instance</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.ExitProperty#getExitForm <em>Exit Form</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.ExitProperty#getFailureMessage <em>Failure Message</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getExitProperty()
 * @model
 * @generated
 */
public interface ExitProperty extends EObject
{
  /**
   * Returns the value of the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' attribute.
   * @see #setComment(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getExitProperty_Comment()
   * @model
   * @generated
   */
  String getComment();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.ExitProperty#getComment <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' attribute.
   * @see #getComment()
   * @generated
   */
  void setComment(String value);

  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getExitProperty_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.ExitProperty#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

  /**
   * Returns the value of the '<em><b>Signal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signal</em>' attribute.
   * @see #setSignal(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getExitProperty_Signal()
   * @model
   * @generated
   */
  String getSignal();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.ExitProperty#getSignal <em>Signal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signal</em>' attribute.
   * @see #getSignal()
   * @generated
   */
  void setSignal(String value);

  /**
   * Returns the value of the '<em><b>Failure Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Failure Name</em>' attribute.
   * @see #setFailureName(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getExitProperty_FailureName()
   * @model
   * @generated
   */
  String getFailureName();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.ExitProperty#getFailureName <em>Failure Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Failure Name</em>' attribute.
   * @see #getFailureName()
   * @generated
   */
  void setFailureName(String value);

  /**
   * Returns the value of the '<em><b>Failure Instance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Failure Instance</em>' attribute.
   * @see #setFailureInstance(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getExitProperty_FailureInstance()
   * @model
   * @generated
   */
  String getFailureInstance();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.ExitProperty#getFailureInstance <em>Failure Instance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Failure Instance</em>' attribute.
   * @see #getFailureInstance()
   * @generated
   */
  void setFailureInstance(String value);

  /**
   * Returns the value of the '<em><b>Exit Form</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exit Form</em>' attribute.
   * @see #setExitForm(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getExitProperty_ExitForm()
   * @model
   * @generated
   */
  String getExitForm();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.ExitProperty#getExitForm <em>Exit Form</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exit Form</em>' attribute.
   * @see #getExitForm()
   * @generated
   */
  void setExitForm(String value);

  /**
   * Returns the value of the '<em><b>Failure Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Failure Message</em>' attribute.
   * @see #setFailureMessage(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getExitProperty_FailureMessage()
   * @model
   * @generated
   */
  String getFailureMessage();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.ExitProperty#getFailureMessage <em>Failure Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Failure Message</em>' attribute.
   * @see #getFailureMessage()
   * @generated
   */
  void setFailureMessage(String value);

} // ExitProperty
