/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exit Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.ExitStep#getExitProps <em>Exit Props</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getExitStep()
 * @model
 * @generated
 */
public interface ExitStep extends Step
{
  /**
   * Returns the value of the '<em><b>Exit Props</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.ExitProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exit Props</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getExitStep_ExitProps()
   * @model containment="true"
   * @generated
   */
  EList<ExitProperty> getExitProps();

} // ExitStep
