/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.webmethods.flow.flowService.FlowServicePackage
 * @generated
 */
public interface FlowServiceFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FlowServiceFactory eINSTANCE = com.webmethods.flow.flowService.impl.FlowServiceFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Flow Service</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flow Service</em>'.
   * @generated
   */
  FlowService createFlowService();

  /**
   * Returns a new object of class '<em>Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Step</em>'.
   * @generated
   */
  Step createStep();

  /**
   * Returns a new object of class '<em>Step Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Step Property</em>'.
   * @generated
   */
  StepProperty createStepProperty();

  /**
   * Returns a new object of class '<em>Comment Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comment Property</em>'.
   * @generated
   */
  CommentProperty createCommentProperty();

  /**
   * Returns a new object of class '<em>Scope Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scope Property</em>'.
   * @generated
   */
  ScopeProperty createScopeProperty();

  /**
   * Returns a new object of class '<em>Timeout Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Timeout Property</em>'.
   * @generated
   */
  TimeoutProperty createTimeoutProperty();

  /**
   * Returns a new object of class '<em>Label Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Label Property</em>'.
   * @generated
   */
  LabelProperty createLabelProperty();

  /**
   * Returns a new object of class '<em>Qualified Service Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Qualified Service Name</em>'.
   * @generated
   */
  QualifiedServiceName createQualifiedServiceName();

  /**
   * Returns a new object of class '<em>Map Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Step</em>'.
   * @generated
   */
  MapStep createMapStep();

  /**
   * Returns a new object of class '<em>Map Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Element</em>'.
   * @generated
   */
  MapElement createMapElement();

  /**
   * Returns a new object of class '<em>Transform Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transform Step</em>'.
   * @generated
   */
  TransformStep createTransformStep();

  /**
   * Returns a new object of class '<em>Drop Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Drop Step</em>'.
   * @generated
   */
  DropStep createDropStep();

  /**
   * Returns a new object of class '<em>Invoke Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invoke Step</em>'.
   * @generated
   */
  InvokeStep createInvokeStep();

  /**
   * Returns a new object of class '<em>Mapping Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mapping Block</em>'.
   * @generated
   */
  MappingBlock createMappingBlock();

  /**
   * Returns a new object of class '<em>Mapping Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mapping Entry</em>'.
   * @generated
   */
  MappingEntry createMappingEntry();

  /**
   * Returns a new object of class '<em>Mapping Copy Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mapping Copy Entry</em>'.
   * @generated
   */
  MappingCopyEntry createMappingCopyEntry();

  /**
   * Returns a new object of class '<em>Mapping Set Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mapping Set Entry</em>'.
   * @generated
   */
  MappingSetEntry createMappingSetEntry();

  /**
   * Returns a new object of class '<em>Invoke Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invoke Property</em>'.
   * @generated
   */
  InvokeProperty createInvokeProperty();

  /**
   * Returns a new object of class '<em>Validate Input</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Validate Input</em>'.
   * @generated
   */
  ValidateInput createValidateInput();

  /**
   * Returns a new object of class '<em>Validate Output</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Validate Output</em>'.
   * @generated
   */
  ValidateOutput createValidateOutput();

  /**
   * Returns a new object of class '<em>Loop Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loop Step</em>'.
   * @generated
   */
  LoopStep createLoopStep();

  /**
   * Returns a new object of class '<em>Loop Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loop Property</em>'.
   * @generated
   */
  LoopProperty createLoopProperty();

  /**
   * Returns a new object of class '<em>Sequence Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sequence Step</em>'.
   * @generated
   */
  SequenceStep createSequenceStep();

  /**
   * Returns a new object of class '<em>Sequence Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sequence Property</em>'.
   * @generated
   */
  SequenceProperty createSequenceProperty();

  /**
   * Returns a new object of class '<em>Try Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Try Step</em>'.
   * @generated
   */
  TryStep createTryStep();

  /**
   * Returns a new object of class '<em>Try Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Try Property</em>'.
   * @generated
   */
  TryProperty createTryProperty();

  /**
   * Returns a new object of class '<em>Catch Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Catch Step</em>'.
   * @generated
   */
  CatchStep createCatchStep();

  /**
   * Returns a new object of class '<em>Catch Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Catch Property</em>'.
   * @generated
   */
  CatchProperty createCatchProperty();

  /**
   * Returns a new object of class '<em>Finally Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Finally Step</em>'.
   * @generated
   */
  FinallyStep createFinallyStep();

  /**
   * Returns a new object of class '<em>Finally Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Finally Property</em>'.
   * @generated
   */
  FinallyProperty createFinallyProperty();

  /**
   * Returns a new object of class '<em>Branch Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Branch Step</em>'.
   * @generated
   */
  BranchStep createBranchStep();

  /**
   * Returns a new object of class '<em>Branch Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Branch Property</em>'.
   * @generated
   */
  BranchProperty createBranchProperty();

  /**
   * Returns a new object of class '<em>Repeat Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Repeat Step</em>'.
   * @generated
   */
  RepeatStep createRepeatStep();

  /**
   * Returns a new object of class '<em>Repeat Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Repeat Property</em>'.
   * @generated
   */
  RepeatProperty createRepeatProperty();

  /**
   * Returns a new object of class '<em>Exit Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exit Step</em>'.
   * @generated
   */
  ExitStep createExitStep();

  /**
   * Returns a new object of class '<em>Exit Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exit Property</em>'.
   * @generated
   */
  ExitProperty createExitProperty();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  FlowServicePackage getFlowServicePackage();

} //FlowServiceFactory
