/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invoke Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.InvokeStep#getService <em>Service</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.InvokeStep#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.InvokeStep#getInvokeProps <em>Invoke Props</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.InvokeStep#getMappings <em>Mappings</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getInvokeStep()
 * @model
 * @generated
 */
public interface InvokeStep extends Step
{
  /**
   * Returns the value of the '<em><b>Service</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service</em>' containment reference.
   * @see #setService(QualifiedServiceName)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getInvokeStep_Service()
   * @model containment="true"
   * @generated
   */
  QualifiedServiceName getService();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.InvokeStep#getService <em>Service</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service</em>' containment reference.
   * @see #getService()
   * @generated
   */
  void setService(QualifiedServiceName value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.StepProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getInvokeStep_Properties()
   * @model containment="true"
   * @generated
   */
  EList<StepProperty> getProperties();

  /**
   * Returns the value of the '<em><b>Invoke Props</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.InvokeProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invoke Props</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getInvokeStep_InvokeProps()
   * @model containment="true"
   * @generated
   */
  EList<InvokeProperty> getInvokeProps();

  /**
   * Returns the value of the '<em><b>Mappings</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.MappingBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mappings</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getInvokeStep_Mappings()
   * @model containment="true"
   * @generated
   */
  EList<MappingBlock> getMappings();

} // InvokeStep
