/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loop Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.LoopProperty#getInput <em>Input</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.LoopProperty#getOutput <em>Output</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getLoopProperty()
 * @model
 * @generated
 */
public interface LoopProperty extends EObject
{
  /**
   * Returns the value of the '<em><b>Input</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input</em>' attribute.
   * @see #setInput(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getLoopProperty_Input()
   * @model
   * @generated
   */
  String getInput();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.LoopProperty#getInput <em>Input</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input</em>' attribute.
   * @see #getInput()
   * @generated
   */
  void setInput(String value);

  /**
   * Returns the value of the '<em><b>Output</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output</em>' attribute.
   * @see #setOutput(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getLoopProperty_Output()
   * @model
   * @generated
   */
  String getOutput();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.LoopProperty#getOutput <em>Output</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output</em>' attribute.
   * @see #getOutput()
   * @generated
   */
  void setOutput(String value);

} // LoopProperty
