/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getMapElement()
 * @model
 * @generated
 */
public interface MapElement extends EObject
{
} // MapElement
