/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapping Copy Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.MappingCopyEntry#getFromPath <em>From Path</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.MappingCopyEntry#getToPath <em>To Path</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getMappingCopyEntry()
 * @model
 * @generated
 */
public interface MappingCopyEntry extends MapElement, MappingEntry
{
  /**
   * Returns the value of the '<em><b>From Path</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Path</em>' attribute list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getMappingCopyEntry_FromPath()
   * @model unique="false"
   * @generated
   */
  EList<String> getFromPath();

  /**
   * Returns the value of the '<em><b>To Path</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Path</em>' attribute list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getMappingCopyEntry_ToPath()
   * @model unique="false"
   * @generated
   */
  EList<String> getToPath();

} // MappingCopyEntry
