/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.MapStep#getMapElements <em>Map Elements</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getMapStep()
 * @model
 * @generated
 */
public interface MapStep extends Step
{
  /**
   * Returns the value of the '<em><b>Map Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.MapElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map Elements</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getMapStep_MapElements()
   * @model containment="true"
   * @generated
   */
  EList<MapElement> getMapElements();

} // MapStep
