/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Qualified Service Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.QualifiedServiceName#getNamespace <em>Namespace</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.QualifiedServiceName#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getQualifiedServiceName()
 * @model
 * @generated
 */
public interface QualifiedServiceName extends EObject
{
  /**
   * Returns the value of the '<em><b>Namespace</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Namespace</em>' attribute list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getQualifiedServiceName_Namespace()
   * @model unique="false"
   * @generated
   */
  EList<String> getNamespace();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getQualifiedServiceName_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.QualifiedServiceName#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // QualifiedServiceName
