/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repeat Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.RepeatProperty#getCount <em>Count</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.RepeatProperty#getInterval <em>Interval</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.RepeatProperty#getOn <em>On</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getRepeatProperty()
 * @model
 * @generated
 */
public interface RepeatProperty extends EObject
{
  /**
   * Returns the value of the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count</em>' attribute.
   * @see #setCount(int)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getRepeatProperty_Count()
   * @model
   * @generated
   */
  int getCount();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.RepeatProperty#getCount <em>Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count</em>' attribute.
   * @see #getCount()
   * @generated
   */
  void setCount(int value);

  /**
   * Returns the value of the '<em><b>Interval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interval</em>' attribute.
   * @see #setInterval(int)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getRepeatProperty_Interval()
   * @model
   * @generated
   */
  int getInterval();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.RepeatProperty#getInterval <em>Interval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interval</em>' attribute.
   * @see #getInterval()
   * @generated
   */
  void setInterval(int value);

  /**
   * Returns the value of the '<em><b>On</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>On</em>' attribute.
   * @see #setOn(String)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getRepeatProperty_On()
   * @model
   * @generated
   */
  String getOn();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.RepeatProperty#getOn <em>On</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>On</em>' attribute.
   * @see #getOn()
   * @generated
   */
  void setOn(String value);

} // RepeatProperty
