/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repeat Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.RepeatStep#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.RepeatStep#getRepeatProps <em>Repeat Props</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.RepeatStep#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getRepeatStep()
 * @model
 * @generated
 */
public interface RepeatStep extends Step
{
  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.StepProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getRepeatStep_Properties()
   * @model containment="true"
   * @generated
   */
  EList<StepProperty> getProperties();

  /**
   * Returns the value of the '<em><b>Repeat Props</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.RepeatProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repeat Props</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getRepeatStep_RepeatProps()
   * @model containment="true"
   * @generated
   */
  EList<RepeatProperty> getRepeatProps();

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.Step}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getRepeatStep_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

} // RepeatStep
