/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sequence Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.SequenceStep#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.SequenceStep#getSeqProps <em>Seq Props</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.SequenceStep#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getSequenceStep()
 * @model
 * @generated
 */
public interface SequenceStep extends Step
{
  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.StepProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getSequenceStep_Properties()
   * @model containment="true"
   * @generated
   */
  EList<StepProperty> getProperties();

  /**
   * Returns the value of the '<em><b>Seq Props</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.SequenceProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seq Props</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getSequenceStep_SeqProps()
   * @model containment="true"
   * @generated
   */
  EList<SequenceProperty> getSeqProps();

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.Step}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getSequenceStep_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

} // SequenceStep
