/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getStepProperty()
 * @model
 * @generated
 */
public interface StepProperty extends MapElement
{
} // StepProperty
