/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Timeout Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.TimeoutProperty#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getTimeoutProperty()
 * @model
 * @generated
 */
public interface TimeoutProperty extends StepProperty
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getTimeoutProperty_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.TimeoutProperty#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // TimeoutProperty
