/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transform Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.TransformStep#getService <em>Service</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.TransformStep#getMappings <em>Mappings</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getTransformStep()
 * @model
 * @generated
 */
public interface TransformStep extends MapElement
{
  /**
   * Returns the value of the '<em><b>Service</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service</em>' containment reference.
   * @see #setService(QualifiedServiceName)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getTransformStep_Service()
   * @model containment="true"
   * @generated
   */
  QualifiedServiceName getService();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.TransformStep#getService <em>Service</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service</em>' containment reference.
   * @see #getService()
   * @generated
   */
  void setService(QualifiedServiceName value);

  /**
   * Returns the value of the '<em><b>Mappings</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.MappingBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mappings</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getTransformStep_Mappings()
   * @model containment="true"
   * @generated
   */
  EList<MappingBlock> getMappings();

} // TransformStep
