/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Try Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.TryStep#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.TryStep#getTryProps <em>Try Props</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.TryStep#getSteps <em>Steps</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.TryStep#getCatches <em>Catches</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.TryStep#getFinallyBlock <em>Finally Block</em>}</li>
 * </ul>
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getTryStep()
 * @model
 * @generated
 */
public interface TryStep extends Step
{
  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.StepProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getTryStep_Properties()
   * @model containment="true"
   * @generated
   */
  EList<StepProperty> getProperties();

  /**
   * Returns the value of the '<em><b>Try Props</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.TryProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Try Props</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getTryStep_TryProps()
   * @model containment="true"
   * @generated
   */
  EList<TryProperty> getTryProps();

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.Step}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getTryStep_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

  /**
   * Returns the value of the '<em><b>Catches</b></em>' containment reference list.
   * The list contents are of type {@link com.webmethods.flow.flowService.CatchStep}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Catches</em>' containment reference list.
   * @see com.webmethods.flow.flowService.FlowServicePackage#getTryStep_Catches()
   * @model containment="true"
   * @generated
   */
  EList<CatchStep> getCatches();

  /**
   * Returns the value of the '<em><b>Finally Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Finally Block</em>' containment reference.
   * @see #setFinallyBlock(FinallyStep)
   * @see com.webmethods.flow.flowService.FlowServicePackage#getTryStep_FinallyBlock()
   * @model containment="true"
   * @generated
   */
  FinallyStep getFinallyBlock();

  /**
   * Sets the value of the '{@link com.webmethods.flow.flowService.TryStep#getFinallyBlock <em>Finally Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Finally Block</em>' containment reference.
   * @see #getFinallyBlock()
   * @generated
   */
  void setFinallyBlock(FinallyStep value);

} // TryStep
