/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Validate Input</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.webmethods.flow.flowService.FlowServicePackage#getValidateInput()
 * @model
 * @generated
 */
public interface ValidateInput extends InvokeProperty
{
} // ValidateInput
