/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService.util;

import com.webmethods.flow.flowService.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see com.webmethods.flow.flowService.FlowServicePackage
 * @generated
 */
public class FlowServiceAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static FlowServicePackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FlowServiceAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = FlowServicePackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FlowServiceSwitch<Adapter> modelSwitch =
    new FlowServiceSwitch<Adapter>()
    {
      @Override
      public Adapter caseModel(Model object)
      {
        return createModelAdapter();
      }
      @Override
      public Adapter caseFlowService(FlowService object)
      {
        return createFlowServiceAdapter();
      }
      @Override
      public Adapter caseStep(Step object)
      {
        return createStepAdapter();
      }
      @Override
      public Adapter caseStepProperty(StepProperty object)
      {
        return createStepPropertyAdapter();
      }
      @Override
      public Adapter caseCommentProperty(CommentProperty object)
      {
        return createCommentPropertyAdapter();
      }
      @Override
      public Adapter caseScopeProperty(ScopeProperty object)
      {
        return createScopePropertyAdapter();
      }
      @Override
      public Adapter caseTimeoutProperty(TimeoutProperty object)
      {
        return createTimeoutPropertyAdapter();
      }
      @Override
      public Adapter caseLabelProperty(LabelProperty object)
      {
        return createLabelPropertyAdapter();
      }
      @Override
      public Adapter caseQualifiedServiceName(QualifiedServiceName object)
      {
        return createQualifiedServiceNameAdapter();
      }
      @Override
      public Adapter caseMapStep(MapStep object)
      {
        return createMapStepAdapter();
      }
      @Override
      public Adapter caseMapElement(MapElement object)
      {
        return createMapElementAdapter();
      }
      @Override
      public Adapter caseTransformStep(TransformStep object)
      {
        return createTransformStepAdapter();
      }
      @Override
      public Adapter caseDropStep(DropStep object)
      {
        return createDropStepAdapter();
      }
      @Override
      public Adapter caseInvokeStep(InvokeStep object)
      {
        return createInvokeStepAdapter();
      }
      @Override
      public Adapter caseMappingBlock(MappingBlock object)
      {
        return createMappingBlockAdapter();
      }
      @Override
      public Adapter caseMappingEntry(MappingEntry object)
      {
        return createMappingEntryAdapter();
      }
      @Override
      public Adapter caseMappingCopyEntry(MappingCopyEntry object)
      {
        return createMappingCopyEntryAdapter();
      }
      @Override
      public Adapter caseMappingSetEntry(MappingSetEntry object)
      {
        return createMappingSetEntryAdapter();
      }
      @Override
      public Adapter caseInvokeProperty(InvokeProperty object)
      {
        return createInvokePropertyAdapter();
      }
      @Override
      public Adapter caseValidateInput(ValidateInput object)
      {
        return createValidateInputAdapter();
      }
      @Override
      public Adapter caseValidateOutput(ValidateOutput object)
      {
        return createValidateOutputAdapter();
      }
      @Override
      public Adapter caseLoopStep(LoopStep object)
      {
        return createLoopStepAdapter();
      }
      @Override
      public Adapter caseLoopProperty(LoopProperty object)
      {
        return createLoopPropertyAdapter();
      }
      @Override
      public Adapter caseSequenceStep(SequenceStep object)
      {
        return createSequenceStepAdapter();
      }
      @Override
      public Adapter caseSequenceProperty(SequenceProperty object)
      {
        return createSequencePropertyAdapter();
      }
      @Override
      public Adapter caseTryStep(TryStep object)
      {
        return createTryStepAdapter();
      }
      @Override
      public Adapter caseTryProperty(TryProperty object)
      {
        return createTryPropertyAdapter();
      }
      @Override
      public Adapter caseCatchStep(CatchStep object)
      {
        return createCatchStepAdapter();
      }
      @Override
      public Adapter caseCatchProperty(CatchProperty object)
      {
        return createCatchPropertyAdapter();
      }
      @Override
      public Adapter caseFinallyStep(FinallyStep object)
      {
        return createFinallyStepAdapter();
      }
      @Override
      public Adapter caseFinallyProperty(FinallyProperty object)
      {
        return createFinallyPropertyAdapter();
      }
      @Override
      public Adapter caseBranchStep(BranchStep object)
      {
        return createBranchStepAdapter();
      }
      @Override
      public Adapter caseBranchProperty(BranchProperty object)
      {
        return createBranchPropertyAdapter();
      }
      @Override
      public Adapter caseRepeatStep(RepeatStep object)
      {
        return createRepeatStepAdapter();
      }
      @Override
      public Adapter caseRepeatProperty(RepeatProperty object)
      {
        return createRepeatPropertyAdapter();
      }
      @Override
      public Adapter caseExitStep(ExitStep object)
      {
        return createExitStepAdapter();
      }
      @Override
      public Adapter caseExitProperty(ExitProperty object)
      {
        return createExitPropertyAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.Model
   * @generated
   */
  public Adapter createModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.FlowService <em>Flow Service</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.FlowService
   * @generated
   */
  public Adapter createFlowServiceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.Step
   * @generated
   */
  public Adapter createStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.StepProperty <em>Step Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.StepProperty
   * @generated
   */
  public Adapter createStepPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.CommentProperty <em>Comment Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.CommentProperty
   * @generated
   */
  public Adapter createCommentPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.ScopeProperty <em>Scope Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.ScopeProperty
   * @generated
   */
  public Adapter createScopePropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.TimeoutProperty <em>Timeout Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.TimeoutProperty
   * @generated
   */
  public Adapter createTimeoutPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.LabelProperty <em>Label Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.LabelProperty
   * @generated
   */
  public Adapter createLabelPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.QualifiedServiceName <em>Qualified Service Name</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.QualifiedServiceName
   * @generated
   */
  public Adapter createQualifiedServiceNameAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.MapStep <em>Map Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.MapStep
   * @generated
   */
  public Adapter createMapStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.MapElement <em>Map Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.MapElement
   * @generated
   */
  public Adapter createMapElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.TransformStep <em>Transform Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.TransformStep
   * @generated
   */
  public Adapter createTransformStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.DropStep <em>Drop Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.DropStep
   * @generated
   */
  public Adapter createDropStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.InvokeStep <em>Invoke Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.InvokeStep
   * @generated
   */
  public Adapter createInvokeStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.MappingBlock <em>Mapping Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.MappingBlock
   * @generated
   */
  public Adapter createMappingBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.MappingEntry <em>Mapping Entry</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.MappingEntry
   * @generated
   */
  public Adapter createMappingEntryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.MappingCopyEntry <em>Mapping Copy Entry</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.MappingCopyEntry
   * @generated
   */
  public Adapter createMappingCopyEntryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.MappingSetEntry <em>Mapping Set Entry</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.MappingSetEntry
   * @generated
   */
  public Adapter createMappingSetEntryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.InvokeProperty <em>Invoke Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.InvokeProperty
   * @generated
   */
  public Adapter createInvokePropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.ValidateInput <em>Validate Input</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.ValidateInput
   * @generated
   */
  public Adapter createValidateInputAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.ValidateOutput <em>Validate Output</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.ValidateOutput
   * @generated
   */
  public Adapter createValidateOutputAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.LoopStep <em>Loop Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.LoopStep
   * @generated
   */
  public Adapter createLoopStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.LoopProperty <em>Loop Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.LoopProperty
   * @generated
   */
  public Adapter createLoopPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.SequenceStep <em>Sequence Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.SequenceStep
   * @generated
   */
  public Adapter createSequenceStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.SequenceProperty <em>Sequence Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.SequenceProperty
   * @generated
   */
  public Adapter createSequencePropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.TryStep <em>Try Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.TryStep
   * @generated
   */
  public Adapter createTryStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.TryProperty <em>Try Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.TryProperty
   * @generated
   */
  public Adapter createTryPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.CatchStep <em>Catch Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.CatchStep
   * @generated
   */
  public Adapter createCatchStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.CatchProperty <em>Catch Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.CatchProperty
   * @generated
   */
  public Adapter createCatchPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.FinallyStep <em>Finally Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.FinallyStep
   * @generated
   */
  public Adapter createFinallyStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.FinallyProperty <em>Finally Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.FinallyProperty
   * @generated
   */
  public Adapter createFinallyPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.BranchStep <em>Branch Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.BranchStep
   * @generated
   */
  public Adapter createBranchStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.BranchProperty <em>Branch Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.BranchProperty
   * @generated
   */
  public Adapter createBranchPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.RepeatStep <em>Repeat Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.RepeatStep
   * @generated
   */
  public Adapter createRepeatStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.RepeatProperty <em>Repeat Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.RepeatProperty
   * @generated
   */
  public Adapter createRepeatPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.ExitStep <em>Exit Step</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.ExitStep
   * @generated
   */
  public Adapter createExitStepAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.webmethods.flow.flowService.ExitProperty <em>Exit Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.webmethods.flow.flowService.ExitProperty
   * @generated
   */
  public Adapter createExitPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //FlowServiceAdapterFactory
