/*
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FlowServiceUiModule extends AbstractFlowServiceUiModule {

	public FlowServiceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
