/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService.impl;

import com.webmethods.flow.flowService.BranchProperty;
import com.webmethods.flow.flowService.FlowServicePackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Branch Property</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.impl.BranchPropertyImpl#getSwitch <em>Switch</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.BranchPropertyImpl#getEval <em>Eval</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BranchPropertyImpl extends MinimalEObjectImpl.Container implements BranchProperty
{
  /**
   * The default value of the '{@link #getSwitch() <em>Switch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSwitch()
   * @generated
   * @ordered
   */
  protected static final String SWITCH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSwitch() <em>Switch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSwitch()
   * @generated
   * @ordered
   */
  protected String switch_ = SWITCH_EDEFAULT;

  /**
   * The default value of the '{@link #getEval() <em>Eval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEval()
   * @generated
   * @ordered
   */
  protected static final String EVAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEval() <em>Eval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEval()
   * @generated
   * @ordered
   */
  protected String eval = EVAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BranchPropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlowServicePackage.Literals.BRANCH_PROPERTY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSwitch()
  {
    return switch_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSwitch(String newSwitch)
  {
    String oldSwitch = switch_;
    switch_ = newSwitch;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FlowServicePackage.BRANCH_PROPERTY__SWITCH, oldSwitch, switch_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEval()
  {
    return eval;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEval(String newEval)
  {
    String oldEval = eval;
    eval = newEval;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FlowServicePackage.BRANCH_PROPERTY__EVAL, oldEval, eval));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlowServicePackage.BRANCH_PROPERTY__SWITCH:
        return getSwitch();
      case FlowServicePackage.BRANCH_PROPERTY__EVAL:
        return getEval();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlowServicePackage.BRANCH_PROPERTY__SWITCH:
        setSwitch((String)newValue);
        return;
      case FlowServicePackage.BRANCH_PROPERTY__EVAL:
        setEval((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.BRANCH_PROPERTY__SWITCH:
        setSwitch(SWITCH_EDEFAULT);
        return;
      case FlowServicePackage.BRANCH_PROPERTY__EVAL:
        setEval(EVAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.BRANCH_PROPERTY__SWITCH:
        return SWITCH_EDEFAULT == null ? switch_ != null : !SWITCH_EDEFAULT.equals(switch_);
      case FlowServicePackage.BRANCH_PROPERTY__EVAL:
        return EVAL_EDEFAULT == null ? eval != null : !EVAL_EDEFAULT.equals(eval);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (switch: ");
    result.append(switch_);
    result.append(", eval: ");
    result.append(eval);
    result.append(')');
    return result.toString();
  }

} //BranchPropertyImpl
