/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService.impl;

import com.webmethods.flow.flowService.CatchProperty;
import com.webmethods.flow.flowService.CatchStep;
import com.webmethods.flow.flowService.FlowServicePackage;
import com.webmethods.flow.flowService.Step;
import com.webmethods.flow.flowService.StepProperty;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Catch Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.impl.CatchStepImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.CatchStepImpl#getCatchProps <em>Catch Props</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.CatchStepImpl#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CatchStepImpl extends MinimalEObjectImpl.Container implements CatchStep
{
  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected EList<StepProperty> properties;

  /**
   * The cached value of the '{@link #getCatchProps() <em>Catch Props</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCatchProps()
   * @generated
   * @ordered
   */
  protected EList<CatchProperty> catchProps;

  /**
   * The cached value of the '{@link #getSteps() <em>Steps</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSteps()
   * @generated
   * @ordered
   */
  protected EList<Step> steps;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CatchStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlowServicePackage.Literals.CATCH_STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StepProperty> getProperties()
  {
    if (properties == null)
    {
      properties = new EObjectContainmentEList<StepProperty>(StepProperty.class, this, FlowServicePackage.CATCH_STEP__PROPERTIES);
    }
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CatchProperty> getCatchProps()
  {
    if (catchProps == null)
    {
      catchProps = new EObjectContainmentEList<CatchProperty>(CatchProperty.class, this, FlowServicePackage.CATCH_STEP__CATCH_PROPS);
    }
    return catchProps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Step> getSteps()
  {
    if (steps == null)
    {
      steps = new EObjectContainmentEList<Step>(Step.class, this, FlowServicePackage.CATCH_STEP__STEPS);
    }
    return steps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FlowServicePackage.CATCH_STEP__PROPERTIES:
        return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
      case FlowServicePackage.CATCH_STEP__CATCH_PROPS:
        return ((InternalEList<?>)getCatchProps()).basicRemove(otherEnd, msgs);
      case FlowServicePackage.CATCH_STEP__STEPS:
        return ((InternalEList<?>)getSteps()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlowServicePackage.CATCH_STEP__PROPERTIES:
        return getProperties();
      case FlowServicePackage.CATCH_STEP__CATCH_PROPS:
        return getCatchProps();
      case FlowServicePackage.CATCH_STEP__STEPS:
        return getSteps();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlowServicePackage.CATCH_STEP__PROPERTIES:
        getProperties().clear();
        getProperties().addAll((Collection<? extends StepProperty>)newValue);
        return;
      case FlowServicePackage.CATCH_STEP__CATCH_PROPS:
        getCatchProps().clear();
        getCatchProps().addAll((Collection<? extends CatchProperty>)newValue);
        return;
      case FlowServicePackage.CATCH_STEP__STEPS:
        getSteps().clear();
        getSteps().addAll((Collection<? extends Step>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.CATCH_STEP__PROPERTIES:
        getProperties().clear();
        return;
      case FlowServicePackage.CATCH_STEP__CATCH_PROPS:
        getCatchProps().clear();
        return;
      case FlowServicePackage.CATCH_STEP__STEPS:
        getSteps().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.CATCH_STEP__PROPERTIES:
        return properties != null && !properties.isEmpty();
      case FlowServicePackage.CATCH_STEP__CATCH_PROPS:
        return catchProps != null && !catchProps.isEmpty();
      case FlowServicePackage.CATCH_STEP__STEPS:
        return steps != null && !steps.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //CatchStepImpl
