/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService.impl;

import com.webmethods.flow.flowService.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class FlowServiceFactoryImpl extends EFactoryImpl implements FlowServiceFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static FlowServiceFactory init()
  {
    try
    {
      FlowServiceFactory theFlowServiceFactory = (FlowServiceFactory)EPackage.Registry.INSTANCE.getEFactory(FlowServicePackage.eNS_URI);
      if (theFlowServiceFactory != null)
      {
        return theFlowServiceFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new FlowServiceFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FlowServiceFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case FlowServicePackage.MODEL: return createModel();
      case FlowServicePackage.FLOW_SERVICE: return createFlowService();
      case FlowServicePackage.STEP: return createStep();
      case FlowServicePackage.STEP_PROPERTY: return createStepProperty();
      case FlowServicePackage.COMMENT_PROPERTY: return createCommentProperty();
      case FlowServicePackage.SCOPE_PROPERTY: return createScopeProperty();
      case FlowServicePackage.TIMEOUT_PROPERTY: return createTimeoutProperty();
      case FlowServicePackage.LABEL_PROPERTY: return createLabelProperty();
      case FlowServicePackage.QUALIFIED_SERVICE_NAME: return createQualifiedServiceName();
      case FlowServicePackage.MAP_STEP: return createMapStep();
      case FlowServicePackage.MAP_ELEMENT: return createMapElement();
      case FlowServicePackage.TRANSFORM_STEP: return createTransformStep();
      case FlowServicePackage.DROP_STEP: return createDropStep();
      case FlowServicePackage.INVOKE_STEP: return createInvokeStep();
      case FlowServicePackage.MAPPING_BLOCK: return createMappingBlock();
      case FlowServicePackage.MAPPING_ENTRY: return createMappingEntry();
      case FlowServicePackage.MAPPING_COPY_ENTRY: return createMappingCopyEntry();
      case FlowServicePackage.MAPPING_SET_ENTRY: return createMappingSetEntry();
      case FlowServicePackage.INVOKE_PROPERTY: return createInvokeProperty();
      case FlowServicePackage.VALIDATE_INPUT: return createValidateInput();
      case FlowServicePackage.VALIDATE_OUTPUT: return createValidateOutput();
      case FlowServicePackage.LOOP_STEP: return createLoopStep();
      case FlowServicePackage.LOOP_PROPERTY: return createLoopProperty();
      case FlowServicePackage.SEQUENCE_STEP: return createSequenceStep();
      case FlowServicePackage.SEQUENCE_PROPERTY: return createSequenceProperty();
      case FlowServicePackage.TRY_STEP: return createTryStep();
      case FlowServicePackage.TRY_PROPERTY: return createTryProperty();
      case FlowServicePackage.CATCH_STEP: return createCatchStep();
      case FlowServicePackage.CATCH_PROPERTY: return createCatchProperty();
      case FlowServicePackage.FINALLY_STEP: return createFinallyStep();
      case FlowServicePackage.FINALLY_PROPERTY: return createFinallyProperty();
      case FlowServicePackage.BRANCH_STEP: return createBranchStep();
      case FlowServicePackage.BRANCH_PROPERTY: return createBranchProperty();
      case FlowServicePackage.REPEAT_STEP: return createRepeatStep();
      case FlowServicePackage.REPEAT_PROPERTY: return createRepeatProperty();
      case FlowServicePackage.EXIT_STEP: return createExitStep();
      case FlowServicePackage.EXIT_PROPERTY: return createExitProperty();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FlowService createFlowService()
  {
    FlowServiceImpl flowService = new FlowServiceImpl();
    return flowService;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Step createStep()
  {
    StepImpl step = new StepImpl();
    return step;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StepProperty createStepProperty()
  {
    StepPropertyImpl stepProperty = new StepPropertyImpl();
    return stepProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CommentProperty createCommentProperty()
  {
    CommentPropertyImpl commentProperty = new CommentPropertyImpl();
    return commentProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ScopeProperty createScopeProperty()
  {
    ScopePropertyImpl scopeProperty = new ScopePropertyImpl();
    return scopeProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TimeoutProperty createTimeoutProperty()
  {
    TimeoutPropertyImpl timeoutProperty = new TimeoutPropertyImpl();
    return timeoutProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LabelProperty createLabelProperty()
  {
    LabelPropertyImpl labelProperty = new LabelPropertyImpl();
    return labelProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QualifiedServiceName createQualifiedServiceName()
  {
    QualifiedServiceNameImpl qualifiedServiceName = new QualifiedServiceNameImpl();
    return qualifiedServiceName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MapStep createMapStep()
  {
    MapStepImpl mapStep = new MapStepImpl();
    return mapStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MapElement createMapElement()
  {
    MapElementImpl mapElement = new MapElementImpl();
    return mapElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TransformStep createTransformStep()
  {
    TransformStepImpl transformStep = new TransformStepImpl();
    return transformStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DropStep createDropStep()
  {
    DropStepImpl dropStep = new DropStepImpl();
    return dropStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InvokeStep createInvokeStep()
  {
    InvokeStepImpl invokeStep = new InvokeStepImpl();
    return invokeStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MappingBlock createMappingBlock()
  {
    MappingBlockImpl mappingBlock = new MappingBlockImpl();
    return mappingBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MappingEntry createMappingEntry()
  {
    MappingEntryImpl mappingEntry = new MappingEntryImpl();
    return mappingEntry;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MappingCopyEntry createMappingCopyEntry()
  {
    MappingCopyEntryImpl mappingCopyEntry = new MappingCopyEntryImpl();
    return mappingCopyEntry;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MappingSetEntry createMappingSetEntry()
  {
    MappingSetEntryImpl mappingSetEntry = new MappingSetEntryImpl();
    return mappingSetEntry;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InvokeProperty createInvokeProperty()
  {
    InvokePropertyImpl invokeProperty = new InvokePropertyImpl();
    return invokeProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ValidateInput createValidateInput()
  {
    ValidateInputImpl validateInput = new ValidateInputImpl();
    return validateInput;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ValidateOutput createValidateOutput()
  {
    ValidateOutputImpl validateOutput = new ValidateOutputImpl();
    return validateOutput;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LoopStep createLoopStep()
  {
    LoopStepImpl loopStep = new LoopStepImpl();
    return loopStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LoopProperty createLoopProperty()
  {
    LoopPropertyImpl loopProperty = new LoopPropertyImpl();
    return loopProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SequenceStep createSequenceStep()
  {
    SequenceStepImpl sequenceStep = new SequenceStepImpl();
    return sequenceStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SequenceProperty createSequenceProperty()
  {
    SequencePropertyImpl sequenceProperty = new SequencePropertyImpl();
    return sequenceProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TryStep createTryStep()
  {
    TryStepImpl tryStep = new TryStepImpl();
    return tryStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TryProperty createTryProperty()
  {
    TryPropertyImpl tryProperty = new TryPropertyImpl();
    return tryProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CatchStep createCatchStep()
  {
    CatchStepImpl catchStep = new CatchStepImpl();
    return catchStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CatchProperty createCatchProperty()
  {
    CatchPropertyImpl catchProperty = new CatchPropertyImpl();
    return catchProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FinallyStep createFinallyStep()
  {
    FinallyStepImpl finallyStep = new FinallyStepImpl();
    return finallyStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FinallyProperty createFinallyProperty()
  {
    FinallyPropertyImpl finallyProperty = new FinallyPropertyImpl();
    return finallyProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BranchStep createBranchStep()
  {
    BranchStepImpl branchStep = new BranchStepImpl();
    return branchStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BranchProperty createBranchProperty()
  {
    BranchPropertyImpl branchProperty = new BranchPropertyImpl();
    return branchProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RepeatStep createRepeatStep()
  {
    RepeatStepImpl repeatStep = new RepeatStepImpl();
    return repeatStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RepeatProperty createRepeatProperty()
  {
    RepeatPropertyImpl repeatProperty = new RepeatPropertyImpl();
    return repeatProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExitStep createExitStep()
  {
    ExitStepImpl exitStep = new ExitStepImpl();
    return exitStep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExitProperty createExitProperty()
  {
    ExitPropertyImpl exitProperty = new ExitPropertyImpl();
    return exitProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FlowServicePackage getFlowServicePackage()
  {
    return (FlowServicePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static FlowServicePackage getPackage()
  {
    return FlowServicePackage.eINSTANCE;
  }

} //FlowServiceFactoryImpl
