/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService.impl;

import com.webmethods.flow.flowService.BranchProperty;
import com.webmethods.flow.flowService.BranchStep;
import com.webmethods.flow.flowService.CatchProperty;
import com.webmethods.flow.flowService.CatchStep;
import com.webmethods.flow.flowService.CommentProperty;
import com.webmethods.flow.flowService.DropStep;
import com.webmethods.flow.flowService.ExitProperty;
import com.webmethods.flow.flowService.ExitStep;
import com.webmethods.flow.flowService.FinallyProperty;
import com.webmethods.flow.flowService.FinallyStep;
import com.webmethods.flow.flowService.FlowService;
import com.webmethods.flow.flowService.FlowServiceFactory;
import com.webmethods.flow.flowService.FlowServicePackage;
import com.webmethods.flow.flowService.InvokeProperty;
import com.webmethods.flow.flowService.InvokeStep;
import com.webmethods.flow.flowService.LabelProperty;
import com.webmethods.flow.flowService.LoopProperty;
import com.webmethods.flow.flowService.LoopStep;
import com.webmethods.flow.flowService.MapElement;
import com.webmethods.flow.flowService.MapStep;
import com.webmethods.flow.flowService.MappingBlock;
import com.webmethods.flow.flowService.MappingCopyEntry;
import com.webmethods.flow.flowService.MappingEntry;
import com.webmethods.flow.flowService.MappingSetEntry;
import com.webmethods.flow.flowService.Model;
import com.webmethods.flow.flowService.QualifiedServiceName;
import com.webmethods.flow.flowService.RepeatProperty;
import com.webmethods.flow.flowService.RepeatStep;
import com.webmethods.flow.flowService.ScopeProperty;
import com.webmethods.flow.flowService.SequenceProperty;
import com.webmethods.flow.flowService.SequenceStep;
import com.webmethods.flow.flowService.Step;
import com.webmethods.flow.flowService.StepProperty;
import com.webmethods.flow.flowService.TimeoutProperty;
import com.webmethods.flow.flowService.TransformStep;
import com.webmethods.flow.flowService.TryProperty;
import com.webmethods.flow.flowService.TryStep;
import com.webmethods.flow.flowService.ValidateInput;
import com.webmethods.flow.flowService.ValidateOutput;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class FlowServicePackageImpl extends EPackageImpl implements FlowServicePackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass flowServiceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stepPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass commentPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass scopePropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass timeoutPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass labelPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass qualifiedServiceNameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mapStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mapElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass transformStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dropStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass invokeStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mappingBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mappingEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mappingCopyEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mappingSetEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass invokePropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass validateInputEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass validateOutputEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass loopStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass loopPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass sequenceStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass sequencePropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tryStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tryPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass catchStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass catchPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass finallyStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass finallyPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass branchStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass branchPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass repeatStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass repeatPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exitStepEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exitPropertyEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see com.webmethods.flow.flowService.FlowServicePackage#eNS_URI
   * @see #init()
   * @generated
   */
  private FlowServicePackageImpl()
  {
    super(eNS_URI, FlowServiceFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link FlowServicePackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static FlowServicePackage init()
  {
    if (isInited) return (FlowServicePackage)EPackage.Registry.INSTANCE.getEPackage(FlowServicePackage.eNS_URI);

    // Obtain or create and register package
    Object registeredFlowServicePackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    FlowServicePackageImpl theFlowServicePackage = registeredFlowServicePackage instanceof FlowServicePackageImpl ? (FlowServicePackageImpl)registeredFlowServicePackage : new FlowServicePackageImpl();

    isInited = true;

    // Create package meta-data objects
    theFlowServicePackage.createPackageContents();

    // Initialize created meta-data
    theFlowServicePackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theFlowServicePackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(FlowServicePackage.eNS_URI, theFlowServicePackage);
    return theFlowServicePackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Services()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFlowService()
  {
    return flowServiceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFlowService_Name()
  {
    return (EAttribute)flowServiceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFlowService_Steps()
  {
    return (EReference)flowServiceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStep()
  {
    return stepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStepProperty()
  {
    return stepPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCommentProperty()
  {
    return commentPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCommentProperty_Value()
  {
    return (EAttribute)commentPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getScopeProperty()
  {
    return scopePropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getScopeProperty_Value()
  {
    return (EAttribute)scopePropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTimeoutProperty()
  {
    return timeoutPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTimeoutProperty_Value()
  {
    return (EAttribute)timeoutPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLabelProperty()
  {
    return labelPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLabelProperty_Value()
  {
    return (EAttribute)labelPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getQualifiedServiceName()
  {
    return qualifiedServiceNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getQualifiedServiceName_Namespace()
  {
    return (EAttribute)qualifiedServiceNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getQualifiedServiceName_Name()
  {
    return (EAttribute)qualifiedServiceNameEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMapStep()
  {
    return mapStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMapStep_MapElements()
  {
    return (EReference)mapStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMapElement()
  {
    return mapElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTransformStep()
  {
    return transformStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTransformStep_Service()
  {
    return (EReference)transformStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTransformStep_Mappings()
  {
    return (EReference)transformStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDropStep()
  {
    return dropStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDropStep_Path()
  {
    return (EAttribute)dropStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInvokeStep()
  {
    return invokeStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInvokeStep_Service()
  {
    return (EReference)invokeStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInvokeStep_Properties()
  {
    return (EReference)invokeStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInvokeStep_InvokeProps()
  {
    return (EReference)invokeStepEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInvokeStep_Mappings()
  {
    return (EReference)invokeStepEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMappingBlock()
  {
    return mappingBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMappingBlock_Entries()
  {
    return (EReference)mappingBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMappingEntry()
  {
    return mappingEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMappingCopyEntry()
  {
    return mappingCopyEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMappingCopyEntry_FromPath()
  {
    return (EAttribute)mappingCopyEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMappingCopyEntry_ToPath()
  {
    return (EAttribute)mappingCopyEntryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMappingSetEntry()
  {
    return mappingSetEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMappingSetEntry_Path()
  {
    return (EAttribute)mappingSetEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMappingSetEntry_Value()
  {
    return (EAttribute)mappingSetEntryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInvokeProperty()
  {
    return invokePropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInvokeProperty_Value()
  {
    return (EAttribute)invokePropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getValidateInput()
  {
    return validateInputEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getValidateOutput()
  {
    return validateOutputEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLoopStep()
  {
    return loopStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLoopStep_Properties()
  {
    return (EReference)loopStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLoopStep_LoopProps()
  {
    return (EReference)loopStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLoopStep_Steps()
  {
    return (EReference)loopStepEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLoopProperty()
  {
    return loopPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLoopProperty_Input()
  {
    return (EAttribute)loopPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLoopProperty_Output()
  {
    return (EAttribute)loopPropertyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSequenceStep()
  {
    return sequenceStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSequenceStep_Properties()
  {
    return (EReference)sequenceStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSequenceStep_SeqProps()
  {
    return (EReference)sequenceStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSequenceStep_Steps()
  {
    return (EReference)sequenceStepEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSequenceProperty()
  {
    return sequencePropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSequenceProperty_Value()
  {
    return (EAttribute)sequencePropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTryStep()
  {
    return tryStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTryStep_Properties()
  {
    return (EReference)tryStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTryStep_TryProps()
  {
    return (EReference)tryStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTryStep_Steps()
  {
    return (EReference)tryStepEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTryStep_Catches()
  {
    return (EReference)tryStepEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTryStep_FinallyBlock()
  {
    return (EReference)tryStepEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTryProperty()
  {
    return tryPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTryProperty_Value()
  {
    return (EAttribute)tryPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCatchStep()
  {
    return catchStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCatchStep_Properties()
  {
    return (EReference)catchStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCatchStep_CatchProps()
  {
    return (EReference)catchStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCatchStep_Steps()
  {
    return (EReference)catchStepEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCatchProperty()
  {
    return catchPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCatchProperty_Exit()
  {
    return (EAttribute)catchPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCatchProperty_Failures()
  {
    return (EAttribute)catchPropertyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCatchProperty_Selection()
  {
    return (EAttribute)catchPropertyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFinallyStep()
  {
    return finallyStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFinallyStep_Properties()
  {
    return (EReference)finallyStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFinallyStep_FinalProps()
  {
    return (EReference)finallyStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFinallyStep_Steps()
  {
    return (EReference)finallyStepEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFinallyProperty()
  {
    return finallyPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFinallyProperty_Value()
  {
    return (EAttribute)finallyPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBranchStep()
  {
    return branchStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBranchStep_Properties()
  {
    return (EReference)branchStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBranchStep_BranchProps()
  {
    return (EReference)branchStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBranchStep_Steps()
  {
    return (EReference)branchStepEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBranchProperty()
  {
    return branchPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBranchProperty_Switch()
  {
    return (EAttribute)branchPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBranchProperty_Eval()
  {
    return (EAttribute)branchPropertyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRepeatStep()
  {
    return repeatStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRepeatStep_Properties()
  {
    return (EReference)repeatStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRepeatStep_RepeatProps()
  {
    return (EReference)repeatStepEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRepeatStep_Steps()
  {
    return (EReference)repeatStepEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRepeatProperty()
  {
    return repeatPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRepeatProperty_Count()
  {
    return (EAttribute)repeatPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRepeatProperty_Interval()
  {
    return (EAttribute)repeatPropertyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRepeatProperty_On()
  {
    return (EAttribute)repeatPropertyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExitStep()
  {
    return exitStepEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExitStep_ExitProps()
  {
    return (EReference)exitStepEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExitProperty()
  {
    return exitPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExitProperty_Comment()
  {
    return (EAttribute)exitPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExitProperty_Label()
  {
    return (EAttribute)exitPropertyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExitProperty_Signal()
  {
    return (EAttribute)exitPropertyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExitProperty_FailureName()
  {
    return (EAttribute)exitPropertyEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExitProperty_FailureInstance()
  {
    return (EAttribute)exitPropertyEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExitProperty_ExitForm()
  {
    return (EAttribute)exitPropertyEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExitProperty_FailureMessage()
  {
    return (EAttribute)exitPropertyEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FlowServiceFactory getFlowServiceFactory()
  {
    return (FlowServiceFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__SERVICES);

    flowServiceEClass = createEClass(FLOW_SERVICE);
    createEAttribute(flowServiceEClass, FLOW_SERVICE__NAME);
    createEReference(flowServiceEClass, FLOW_SERVICE__STEPS);

    stepEClass = createEClass(STEP);

    stepPropertyEClass = createEClass(STEP_PROPERTY);

    commentPropertyEClass = createEClass(COMMENT_PROPERTY);
    createEAttribute(commentPropertyEClass, COMMENT_PROPERTY__VALUE);

    scopePropertyEClass = createEClass(SCOPE_PROPERTY);
    createEAttribute(scopePropertyEClass, SCOPE_PROPERTY__VALUE);

    timeoutPropertyEClass = createEClass(TIMEOUT_PROPERTY);
    createEAttribute(timeoutPropertyEClass, TIMEOUT_PROPERTY__VALUE);

    labelPropertyEClass = createEClass(LABEL_PROPERTY);
    createEAttribute(labelPropertyEClass, LABEL_PROPERTY__VALUE);

    qualifiedServiceNameEClass = createEClass(QUALIFIED_SERVICE_NAME);
    createEAttribute(qualifiedServiceNameEClass, QUALIFIED_SERVICE_NAME__NAMESPACE);
    createEAttribute(qualifiedServiceNameEClass, QUALIFIED_SERVICE_NAME__NAME);

    mapStepEClass = createEClass(MAP_STEP);
    createEReference(mapStepEClass, MAP_STEP__MAP_ELEMENTS);

    mapElementEClass = createEClass(MAP_ELEMENT);

    transformStepEClass = createEClass(TRANSFORM_STEP);
    createEReference(transformStepEClass, TRANSFORM_STEP__SERVICE);
    createEReference(transformStepEClass, TRANSFORM_STEP__MAPPINGS);

    dropStepEClass = createEClass(DROP_STEP);
    createEAttribute(dropStepEClass, DROP_STEP__PATH);

    invokeStepEClass = createEClass(INVOKE_STEP);
    createEReference(invokeStepEClass, INVOKE_STEP__SERVICE);
    createEReference(invokeStepEClass, INVOKE_STEP__PROPERTIES);
    createEReference(invokeStepEClass, INVOKE_STEP__INVOKE_PROPS);
    createEReference(invokeStepEClass, INVOKE_STEP__MAPPINGS);

    mappingBlockEClass = createEClass(MAPPING_BLOCK);
    createEReference(mappingBlockEClass, MAPPING_BLOCK__ENTRIES);

    mappingEntryEClass = createEClass(MAPPING_ENTRY);

    mappingCopyEntryEClass = createEClass(MAPPING_COPY_ENTRY);
    createEAttribute(mappingCopyEntryEClass, MAPPING_COPY_ENTRY__FROM_PATH);
    createEAttribute(mappingCopyEntryEClass, MAPPING_COPY_ENTRY__TO_PATH);

    mappingSetEntryEClass = createEClass(MAPPING_SET_ENTRY);
    createEAttribute(mappingSetEntryEClass, MAPPING_SET_ENTRY__PATH);
    createEAttribute(mappingSetEntryEClass, MAPPING_SET_ENTRY__VALUE);

    invokePropertyEClass = createEClass(INVOKE_PROPERTY);
    createEAttribute(invokePropertyEClass, INVOKE_PROPERTY__VALUE);

    validateInputEClass = createEClass(VALIDATE_INPUT);

    validateOutputEClass = createEClass(VALIDATE_OUTPUT);

    loopStepEClass = createEClass(LOOP_STEP);
    createEReference(loopStepEClass, LOOP_STEP__PROPERTIES);
    createEReference(loopStepEClass, LOOP_STEP__LOOP_PROPS);
    createEReference(loopStepEClass, LOOP_STEP__STEPS);

    loopPropertyEClass = createEClass(LOOP_PROPERTY);
    createEAttribute(loopPropertyEClass, LOOP_PROPERTY__INPUT);
    createEAttribute(loopPropertyEClass, LOOP_PROPERTY__OUTPUT);

    sequenceStepEClass = createEClass(SEQUENCE_STEP);
    createEReference(sequenceStepEClass, SEQUENCE_STEP__PROPERTIES);
    createEReference(sequenceStepEClass, SEQUENCE_STEP__SEQ_PROPS);
    createEReference(sequenceStepEClass, SEQUENCE_STEP__STEPS);

    sequencePropertyEClass = createEClass(SEQUENCE_PROPERTY);
    createEAttribute(sequencePropertyEClass, SEQUENCE_PROPERTY__VALUE);

    tryStepEClass = createEClass(TRY_STEP);
    createEReference(tryStepEClass, TRY_STEP__PROPERTIES);
    createEReference(tryStepEClass, TRY_STEP__TRY_PROPS);
    createEReference(tryStepEClass, TRY_STEP__STEPS);
    createEReference(tryStepEClass, TRY_STEP__CATCHES);
    createEReference(tryStepEClass, TRY_STEP__FINALLY_BLOCK);

    tryPropertyEClass = createEClass(TRY_PROPERTY);
    createEAttribute(tryPropertyEClass, TRY_PROPERTY__VALUE);

    catchStepEClass = createEClass(CATCH_STEP);
    createEReference(catchStepEClass, CATCH_STEP__PROPERTIES);
    createEReference(catchStepEClass, CATCH_STEP__CATCH_PROPS);
    createEReference(catchStepEClass, CATCH_STEP__STEPS);

    catchPropertyEClass = createEClass(CATCH_PROPERTY);
    createEAttribute(catchPropertyEClass, CATCH_PROPERTY__EXIT);
    createEAttribute(catchPropertyEClass, CATCH_PROPERTY__FAILURES);
    createEAttribute(catchPropertyEClass, CATCH_PROPERTY__SELECTION);

    finallyStepEClass = createEClass(FINALLY_STEP);
    createEReference(finallyStepEClass, FINALLY_STEP__PROPERTIES);
    createEReference(finallyStepEClass, FINALLY_STEP__FINAL_PROPS);
    createEReference(finallyStepEClass, FINALLY_STEP__STEPS);

    finallyPropertyEClass = createEClass(FINALLY_PROPERTY);
    createEAttribute(finallyPropertyEClass, FINALLY_PROPERTY__VALUE);

    branchStepEClass = createEClass(BRANCH_STEP);
    createEReference(branchStepEClass, BRANCH_STEP__PROPERTIES);
    createEReference(branchStepEClass, BRANCH_STEP__BRANCH_PROPS);
    createEReference(branchStepEClass, BRANCH_STEP__STEPS);

    branchPropertyEClass = createEClass(BRANCH_PROPERTY);
    createEAttribute(branchPropertyEClass, BRANCH_PROPERTY__SWITCH);
    createEAttribute(branchPropertyEClass, BRANCH_PROPERTY__EVAL);

    repeatStepEClass = createEClass(REPEAT_STEP);
    createEReference(repeatStepEClass, REPEAT_STEP__PROPERTIES);
    createEReference(repeatStepEClass, REPEAT_STEP__REPEAT_PROPS);
    createEReference(repeatStepEClass, REPEAT_STEP__STEPS);

    repeatPropertyEClass = createEClass(REPEAT_PROPERTY);
    createEAttribute(repeatPropertyEClass, REPEAT_PROPERTY__COUNT);
    createEAttribute(repeatPropertyEClass, REPEAT_PROPERTY__INTERVAL);
    createEAttribute(repeatPropertyEClass, REPEAT_PROPERTY__ON);

    exitStepEClass = createEClass(EXIT_STEP);
    createEReference(exitStepEClass, EXIT_STEP__EXIT_PROPS);

    exitPropertyEClass = createEClass(EXIT_PROPERTY);
    createEAttribute(exitPropertyEClass, EXIT_PROPERTY__COMMENT);
    createEAttribute(exitPropertyEClass, EXIT_PROPERTY__LABEL);
    createEAttribute(exitPropertyEClass, EXIT_PROPERTY__SIGNAL);
    createEAttribute(exitPropertyEClass, EXIT_PROPERTY__FAILURE_NAME);
    createEAttribute(exitPropertyEClass, EXIT_PROPERTY__FAILURE_INSTANCE);
    createEAttribute(exitPropertyEClass, EXIT_PROPERTY__EXIT_FORM);
    createEAttribute(exitPropertyEClass, EXIT_PROPERTY__FAILURE_MESSAGE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    stepPropertyEClass.getESuperTypes().add(this.getMapElement());
    commentPropertyEClass.getESuperTypes().add(this.getStepProperty());
    scopePropertyEClass.getESuperTypes().add(this.getStepProperty());
    timeoutPropertyEClass.getESuperTypes().add(this.getStepProperty());
    labelPropertyEClass.getESuperTypes().add(this.getStepProperty());
    mapStepEClass.getESuperTypes().add(this.getStep());
    transformStepEClass.getESuperTypes().add(this.getMapElement());
    dropStepEClass.getESuperTypes().add(this.getMapElement());
    invokeStepEClass.getESuperTypes().add(this.getStep());
    mappingCopyEntryEClass.getESuperTypes().add(this.getMapElement());
    mappingCopyEntryEClass.getESuperTypes().add(this.getMappingEntry());
    mappingSetEntryEClass.getESuperTypes().add(this.getMapElement());
    mappingSetEntryEClass.getESuperTypes().add(this.getMappingEntry());
    validateInputEClass.getESuperTypes().add(this.getInvokeProperty());
    validateOutputEClass.getESuperTypes().add(this.getInvokeProperty());
    loopStepEClass.getESuperTypes().add(this.getStep());
    sequenceStepEClass.getESuperTypes().add(this.getStep());
    tryStepEClass.getESuperTypes().add(this.getStep());
    branchStepEClass.getESuperTypes().add(this.getStep());
    repeatStepEClass.getESuperTypes().add(this.getStep());
    exitStepEClass.getESuperTypes().add(this.getStep());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Services(), this.getFlowService(), null, "services", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(flowServiceEClass, FlowService.class, "FlowService", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFlowService_Name(), ecorePackage.getEString(), "name", null, 0, 1, FlowService.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFlowService_Steps(), this.getStep(), null, "steps", null, 0, -1, FlowService.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stepEClass, Step.class, "Step", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(stepPropertyEClass, StepProperty.class, "StepProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(commentPropertyEClass, CommentProperty.class, "CommentProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCommentProperty_Value(), ecorePackage.getEString(), "value", null, 0, 1, CommentProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(scopePropertyEClass, ScopeProperty.class, "ScopeProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getScopeProperty_Value(), ecorePackage.getEString(), "value", null, 0, 1, ScopeProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(timeoutPropertyEClass, TimeoutProperty.class, "TimeoutProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTimeoutProperty_Value(), ecorePackage.getEInt(), "value", null, 0, 1, TimeoutProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(labelPropertyEClass, LabelProperty.class, "LabelProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLabelProperty_Value(), ecorePackage.getEString(), "value", null, 0, 1, LabelProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(qualifiedServiceNameEClass, QualifiedServiceName.class, "QualifiedServiceName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getQualifiedServiceName_Namespace(), ecorePackage.getEString(), "namespace", null, 0, -1, QualifiedServiceName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getQualifiedServiceName_Name(), ecorePackage.getEString(), "name", null, 0, 1, QualifiedServiceName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mapStepEClass, MapStep.class, "MapStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMapStep_MapElements(), this.getMapElement(), null, "mapElements", null, 0, -1, MapStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mapElementEClass, MapElement.class, "MapElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(transformStepEClass, TransformStep.class, "TransformStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTransformStep_Service(), this.getQualifiedServiceName(), null, "service", null, 0, 1, TransformStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTransformStep_Mappings(), this.getMappingBlock(), null, "mappings", null, 0, -1, TransformStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dropStepEClass, DropStep.class, "DropStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDropStep_Path(), ecorePackage.getEString(), "path", null, 0, -1, DropStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(invokeStepEClass, InvokeStep.class, "InvokeStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInvokeStep_Service(), this.getQualifiedServiceName(), null, "service", null, 0, 1, InvokeStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInvokeStep_Properties(), this.getStepProperty(), null, "properties", null, 0, -1, InvokeStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInvokeStep_InvokeProps(), this.getInvokeProperty(), null, "invokeProps", null, 0, -1, InvokeStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInvokeStep_Mappings(), this.getMappingBlock(), null, "mappings", null, 0, -1, InvokeStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mappingBlockEClass, MappingBlock.class, "MappingBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMappingBlock_Entries(), this.getMappingEntry(), null, "entries", null, 0, -1, MappingBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mappingEntryEClass, MappingEntry.class, "MappingEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(mappingCopyEntryEClass, MappingCopyEntry.class, "MappingCopyEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMappingCopyEntry_FromPath(), ecorePackage.getEString(), "fromPath", null, 0, -1, MappingCopyEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMappingCopyEntry_ToPath(), ecorePackage.getEString(), "toPath", null, 0, -1, MappingCopyEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mappingSetEntryEClass, MappingSetEntry.class, "MappingSetEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMappingSetEntry_Path(), ecorePackage.getEString(), "path", null, 0, -1, MappingSetEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMappingSetEntry_Value(), ecorePackage.getEString(), "value", null, 0, 1, MappingSetEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(invokePropertyEClass, InvokeProperty.class, "InvokeProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInvokeProperty_Value(), ecorePackage.getEString(), "value", null, 0, 1, InvokeProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(validateInputEClass, ValidateInput.class, "ValidateInput", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(validateOutputEClass, ValidateOutput.class, "ValidateOutput", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(loopStepEClass, LoopStep.class, "LoopStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLoopStep_Properties(), this.getStepProperty(), null, "properties", null, 0, -1, LoopStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLoopStep_LoopProps(), this.getLoopProperty(), null, "loopProps", null, 0, -1, LoopStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLoopStep_Steps(), this.getStep(), null, "steps", null, 0, -1, LoopStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(loopPropertyEClass, LoopProperty.class, "LoopProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLoopProperty_Input(), ecorePackage.getEString(), "input", null, 0, 1, LoopProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLoopProperty_Output(), ecorePackage.getEString(), "output", null, 0, 1, LoopProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(sequenceStepEClass, SequenceStep.class, "SequenceStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSequenceStep_Properties(), this.getStepProperty(), null, "properties", null, 0, -1, SequenceStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSequenceStep_SeqProps(), this.getSequenceProperty(), null, "seqProps", null, 0, -1, SequenceStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSequenceStep_Steps(), this.getStep(), null, "steps", null, 0, -1, SequenceStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(sequencePropertyEClass, SequenceProperty.class, "SequenceProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSequenceProperty_Value(), ecorePackage.getEString(), "value", null, 0, 1, SequenceProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(tryStepEClass, TryStep.class, "TryStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTryStep_Properties(), this.getStepProperty(), null, "properties", null, 0, -1, TryStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTryStep_TryProps(), this.getTryProperty(), null, "tryProps", null, 0, -1, TryStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTryStep_Steps(), this.getStep(), null, "steps", null, 0, -1, TryStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTryStep_Catches(), this.getCatchStep(), null, "catches", null, 0, -1, TryStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTryStep_FinallyBlock(), this.getFinallyStep(), null, "finallyBlock", null, 0, 1, TryStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(tryPropertyEClass, TryProperty.class, "TryProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTryProperty_Value(), ecorePackage.getEString(), "value", null, 0, 1, TryProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(catchStepEClass, CatchStep.class, "CatchStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCatchStep_Properties(), this.getStepProperty(), null, "properties", null, 0, -1, CatchStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCatchStep_CatchProps(), this.getCatchProperty(), null, "catchProps", null, 0, -1, CatchStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCatchStep_Steps(), this.getStep(), null, "steps", null, 0, -1, CatchStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(catchPropertyEClass, CatchProperty.class, "CatchProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCatchProperty_Exit(), ecorePackage.getEString(), "exit", null, 0, 1, CatchProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCatchProperty_Failures(), ecorePackage.getEString(), "failures", null, 0, 1, CatchProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCatchProperty_Selection(), ecorePackage.getEString(), "selection", null, 0, 1, CatchProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(finallyStepEClass, FinallyStep.class, "FinallyStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFinallyStep_Properties(), this.getStepProperty(), null, "properties", null, 0, -1, FinallyStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFinallyStep_FinalProps(), this.getFinallyProperty(), null, "finalProps", null, 0, -1, FinallyStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFinallyStep_Steps(), this.getStep(), null, "steps", null, 0, -1, FinallyStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(finallyPropertyEClass, FinallyProperty.class, "FinallyProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFinallyProperty_Value(), ecorePackage.getEString(), "value", null, 0, 1, FinallyProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(branchStepEClass, BranchStep.class, "BranchStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBranchStep_Properties(), this.getStepProperty(), null, "properties", null, 0, -1, BranchStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBranchStep_BranchProps(), this.getBranchProperty(), null, "branchProps", null, 0, -1, BranchStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBranchStep_Steps(), this.getStep(), null, "steps", null, 0, -1, BranchStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(branchPropertyEClass, BranchProperty.class, "BranchProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBranchProperty_Switch(), ecorePackage.getEString(), "switch", null, 0, 1, BranchProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBranchProperty_Eval(), ecorePackage.getEString(), "eval", null, 0, 1, BranchProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(repeatStepEClass, RepeatStep.class, "RepeatStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRepeatStep_Properties(), this.getStepProperty(), null, "properties", null, 0, -1, RepeatStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRepeatStep_RepeatProps(), this.getRepeatProperty(), null, "repeatProps", null, 0, -1, RepeatStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRepeatStep_Steps(), this.getStep(), null, "steps", null, 0, -1, RepeatStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(repeatPropertyEClass, RepeatProperty.class, "RepeatProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRepeatProperty_Count(), ecorePackage.getEInt(), "count", null, 0, 1, RepeatProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRepeatProperty_Interval(), ecorePackage.getEInt(), "interval", null, 0, 1, RepeatProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRepeatProperty_On(), ecorePackage.getEString(), "on", null, 0, 1, RepeatProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(exitStepEClass, ExitStep.class, "ExitStep", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExitStep_ExitProps(), this.getExitProperty(), null, "exitProps", null, 0, -1, ExitStep.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(exitPropertyEClass, ExitProperty.class, "ExitProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExitProperty_Comment(), ecorePackage.getEString(), "comment", null, 0, 1, ExitProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExitProperty_Label(), ecorePackage.getEString(), "label", null, 0, 1, ExitProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExitProperty_Signal(), ecorePackage.getEString(), "signal", null, 0, 1, ExitProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExitProperty_FailureName(), ecorePackage.getEString(), "failureName", null, 0, 1, ExitProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExitProperty_FailureInstance(), ecorePackage.getEString(), "failureInstance", null, 0, 1, ExitProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExitProperty_ExitForm(), ecorePackage.getEString(), "exitForm", null, 0, 1, ExitProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExitProperty_FailureMessage(), ecorePackage.getEString(), "failureMessage", null, 0, 1, ExitProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //FlowServicePackageImpl
