/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService.impl;

import com.webmethods.flow.flowService.FlowServicePackage;
import com.webmethods.flow.flowService.InvokeProperty;
import com.webmethods.flow.flowService.InvokeStep;
import com.webmethods.flow.flowService.MappingBlock;
import com.webmethods.flow.flowService.QualifiedServiceName;
import com.webmethods.flow.flowService.StepProperty;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Invoke Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.impl.InvokeStepImpl#getService <em>Service</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.InvokeStepImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.InvokeStepImpl#getInvokeProps <em>Invoke Props</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.InvokeStepImpl#getMappings <em>Mappings</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InvokeStepImpl extends StepImpl implements InvokeStep
{
  /**
   * The cached value of the '{@link #getService() <em>Service</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getService()
   * @generated
   * @ordered
   */
  protected QualifiedServiceName service;

  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected EList<StepProperty> properties;

  /**
   * The cached value of the '{@link #getInvokeProps() <em>Invoke Props</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInvokeProps()
   * @generated
   * @ordered
   */
  protected EList<InvokeProperty> invokeProps;

  /**
   * The cached value of the '{@link #getMappings() <em>Mappings</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMappings()
   * @generated
   * @ordered
   */
  protected EList<MappingBlock> mappings;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InvokeStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlowServicePackage.Literals.INVOKE_STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QualifiedServiceName getService()
  {
    return service;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetService(QualifiedServiceName newService, NotificationChain msgs)
  {
    QualifiedServiceName oldService = service;
    service = newService;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FlowServicePackage.INVOKE_STEP__SERVICE, oldService, newService);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setService(QualifiedServiceName newService)
  {
    if (newService != service)
    {
      NotificationChain msgs = null;
      if (service != null)
        msgs = ((InternalEObject)service).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FlowServicePackage.INVOKE_STEP__SERVICE, null, msgs);
      if (newService != null)
        msgs = ((InternalEObject)newService).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FlowServicePackage.INVOKE_STEP__SERVICE, null, msgs);
      msgs = basicSetService(newService, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FlowServicePackage.INVOKE_STEP__SERVICE, newService, newService));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StepProperty> getProperties()
  {
    if (properties == null)
    {
      properties = new EObjectContainmentEList<StepProperty>(StepProperty.class, this, FlowServicePackage.INVOKE_STEP__PROPERTIES);
    }
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InvokeProperty> getInvokeProps()
  {
    if (invokeProps == null)
    {
      invokeProps = new EObjectContainmentEList<InvokeProperty>(InvokeProperty.class, this, FlowServicePackage.INVOKE_STEP__INVOKE_PROPS);
    }
    return invokeProps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MappingBlock> getMappings()
  {
    if (mappings == null)
    {
      mappings = new EObjectContainmentEList<MappingBlock>(MappingBlock.class, this, FlowServicePackage.INVOKE_STEP__MAPPINGS);
    }
    return mappings;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FlowServicePackage.INVOKE_STEP__SERVICE:
        return basicSetService(null, msgs);
      case FlowServicePackage.INVOKE_STEP__PROPERTIES:
        return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
      case FlowServicePackage.INVOKE_STEP__INVOKE_PROPS:
        return ((InternalEList<?>)getInvokeProps()).basicRemove(otherEnd, msgs);
      case FlowServicePackage.INVOKE_STEP__MAPPINGS:
        return ((InternalEList<?>)getMappings()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlowServicePackage.INVOKE_STEP__SERVICE:
        return getService();
      case FlowServicePackage.INVOKE_STEP__PROPERTIES:
        return getProperties();
      case FlowServicePackage.INVOKE_STEP__INVOKE_PROPS:
        return getInvokeProps();
      case FlowServicePackage.INVOKE_STEP__MAPPINGS:
        return getMappings();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlowServicePackage.INVOKE_STEP__SERVICE:
        setService((QualifiedServiceName)newValue);
        return;
      case FlowServicePackage.INVOKE_STEP__PROPERTIES:
        getProperties().clear();
        getProperties().addAll((Collection<? extends StepProperty>)newValue);
        return;
      case FlowServicePackage.INVOKE_STEP__INVOKE_PROPS:
        getInvokeProps().clear();
        getInvokeProps().addAll((Collection<? extends InvokeProperty>)newValue);
        return;
      case FlowServicePackage.INVOKE_STEP__MAPPINGS:
        getMappings().clear();
        getMappings().addAll((Collection<? extends MappingBlock>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.INVOKE_STEP__SERVICE:
        setService((QualifiedServiceName)null);
        return;
      case FlowServicePackage.INVOKE_STEP__PROPERTIES:
        getProperties().clear();
        return;
      case FlowServicePackage.INVOKE_STEP__INVOKE_PROPS:
        getInvokeProps().clear();
        return;
      case FlowServicePackage.INVOKE_STEP__MAPPINGS:
        getMappings().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.INVOKE_STEP__SERVICE:
        return service != null;
      case FlowServicePackage.INVOKE_STEP__PROPERTIES:
        return properties != null && !properties.isEmpty();
      case FlowServicePackage.INVOKE_STEP__INVOKE_PROPS:
        return invokeProps != null && !invokeProps.isEmpty();
      case FlowServicePackage.INVOKE_STEP__MAPPINGS:
        return mappings != null && !mappings.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //InvokeStepImpl
