/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService.impl;

import com.webmethods.flow.flowService.FlowServicePackage;
import com.webmethods.flow.flowService.LoopProperty;
import com.webmethods.flow.flowService.LoopStep;
import com.webmethods.flow.flowService.Step;
import com.webmethods.flow.flowService.StepProperty;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Loop Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.impl.LoopStepImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.LoopStepImpl#getLoopProps <em>Loop Props</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.LoopStepImpl#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LoopStepImpl extends StepImpl implements LoopStep
{
  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected EList<StepProperty> properties;

  /**
   * The cached value of the '{@link #getLoopProps() <em>Loop Props</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoopProps()
   * @generated
   * @ordered
   */
  protected EList<LoopProperty> loopProps;

  /**
   * The cached value of the '{@link #getSteps() <em>Steps</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSteps()
   * @generated
   * @ordered
   */
  protected EList<Step> steps;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LoopStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlowServicePackage.Literals.LOOP_STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StepProperty> getProperties()
  {
    if (properties == null)
    {
      properties = new EObjectContainmentEList<StepProperty>(StepProperty.class, this, FlowServicePackage.LOOP_STEP__PROPERTIES);
    }
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LoopProperty> getLoopProps()
  {
    if (loopProps == null)
    {
      loopProps = new EObjectContainmentEList<LoopProperty>(LoopProperty.class, this, FlowServicePackage.LOOP_STEP__LOOP_PROPS);
    }
    return loopProps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Step> getSteps()
  {
    if (steps == null)
    {
      steps = new EObjectContainmentEList<Step>(Step.class, this, FlowServicePackage.LOOP_STEP__STEPS);
    }
    return steps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FlowServicePackage.LOOP_STEP__PROPERTIES:
        return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
      case FlowServicePackage.LOOP_STEP__LOOP_PROPS:
        return ((InternalEList<?>)getLoopProps()).basicRemove(otherEnd, msgs);
      case FlowServicePackage.LOOP_STEP__STEPS:
        return ((InternalEList<?>)getSteps()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlowServicePackage.LOOP_STEP__PROPERTIES:
        return getProperties();
      case FlowServicePackage.LOOP_STEP__LOOP_PROPS:
        return getLoopProps();
      case FlowServicePackage.LOOP_STEP__STEPS:
        return getSteps();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlowServicePackage.LOOP_STEP__PROPERTIES:
        getProperties().clear();
        getProperties().addAll((Collection<? extends StepProperty>)newValue);
        return;
      case FlowServicePackage.LOOP_STEP__LOOP_PROPS:
        getLoopProps().clear();
        getLoopProps().addAll((Collection<? extends LoopProperty>)newValue);
        return;
      case FlowServicePackage.LOOP_STEP__STEPS:
        getSteps().clear();
        getSteps().addAll((Collection<? extends Step>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.LOOP_STEP__PROPERTIES:
        getProperties().clear();
        return;
      case FlowServicePackage.LOOP_STEP__LOOP_PROPS:
        getLoopProps().clear();
        return;
      case FlowServicePackage.LOOP_STEP__STEPS:
        getSteps().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.LOOP_STEP__PROPERTIES:
        return properties != null && !properties.isEmpty();
      case FlowServicePackage.LOOP_STEP__LOOP_PROPS:
        return loopProps != null && !loopProps.isEmpty();
      case FlowServicePackage.LOOP_STEP__STEPS:
        return steps != null && !steps.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //LoopStepImpl
