/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService.impl;

import com.webmethods.flow.flowService.FlowServicePackage;
import com.webmethods.flow.flowService.MappingCopyEntry;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mapping Copy Entry</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.impl.MappingCopyEntryImpl#getFromPath <em>From Path</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.MappingCopyEntryImpl#getToPath <em>To Path</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MappingCopyEntryImpl extends MapElementImpl implements MappingCopyEntry
{
  /**
   * The cached value of the '{@link #getFromPath() <em>From Path</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromPath()
   * @generated
   * @ordered
   */
  protected EList<String> fromPath;

  /**
   * The cached value of the '{@link #getToPath() <em>To Path</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToPath()
   * @generated
   * @ordered
   */
  protected EList<String> toPath;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MappingCopyEntryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlowServicePackage.Literals.MAPPING_COPY_ENTRY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getFromPath()
  {
    if (fromPath == null)
    {
      fromPath = new EDataTypeEList<String>(String.class, this, FlowServicePackage.MAPPING_COPY_ENTRY__FROM_PATH);
    }
    return fromPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getToPath()
  {
    if (toPath == null)
    {
      toPath = new EDataTypeEList<String>(String.class, this, FlowServicePackage.MAPPING_COPY_ENTRY__TO_PATH);
    }
    return toPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlowServicePackage.MAPPING_COPY_ENTRY__FROM_PATH:
        return getFromPath();
      case FlowServicePackage.MAPPING_COPY_ENTRY__TO_PATH:
        return getToPath();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlowServicePackage.MAPPING_COPY_ENTRY__FROM_PATH:
        getFromPath().clear();
        getFromPath().addAll((Collection<? extends String>)newValue);
        return;
      case FlowServicePackage.MAPPING_COPY_ENTRY__TO_PATH:
        getToPath().clear();
        getToPath().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.MAPPING_COPY_ENTRY__FROM_PATH:
        getFromPath().clear();
        return;
      case FlowServicePackage.MAPPING_COPY_ENTRY__TO_PATH:
        getToPath().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.MAPPING_COPY_ENTRY__FROM_PATH:
        return fromPath != null && !fromPath.isEmpty();
      case FlowServicePackage.MAPPING_COPY_ENTRY__TO_PATH:
        return toPath != null && !toPath.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (fromPath: ");
    result.append(fromPath);
    result.append(", toPath: ");
    result.append(toPath);
    result.append(')');
    return result.toString();
  }

} //MappingCopyEntryImpl
