/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService.impl;

import com.webmethods.flow.flowService.CatchStep;
import com.webmethods.flow.flowService.FinallyStep;
import com.webmethods.flow.flowService.FlowServicePackage;
import com.webmethods.flow.flowService.Step;
import com.webmethods.flow.flowService.StepProperty;
import com.webmethods.flow.flowService.TryProperty;
import com.webmethods.flow.flowService.TryStep;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Try Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.webmethods.flow.flowService.impl.TryStepImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.TryStepImpl#getTryProps <em>Try Props</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.TryStepImpl#getSteps <em>Steps</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.TryStepImpl#getCatches <em>Catches</em>}</li>
 *   <li>{@link com.webmethods.flow.flowService.impl.TryStepImpl#getFinallyBlock <em>Finally Block</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TryStepImpl extends StepImpl implements TryStep
{
  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected EList<StepProperty> properties;

  /**
   * The cached value of the '{@link #getTryProps() <em>Try Props</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTryProps()
   * @generated
   * @ordered
   */
  protected EList<TryProperty> tryProps;

  /**
   * The cached value of the '{@link #getSteps() <em>Steps</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSteps()
   * @generated
   * @ordered
   */
  protected EList<Step> steps;

  /**
   * The cached value of the '{@link #getCatches() <em>Catches</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCatches()
   * @generated
   * @ordered
   */
  protected EList<CatchStep> catches;

  /**
   * The cached value of the '{@link #getFinallyBlock() <em>Finally Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFinallyBlock()
   * @generated
   * @ordered
   */
  protected FinallyStep finallyBlock;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TryStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlowServicePackage.Literals.TRY_STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StepProperty> getProperties()
  {
    if (properties == null)
    {
      properties = new EObjectContainmentEList<StepProperty>(StepProperty.class, this, FlowServicePackage.TRY_STEP__PROPERTIES);
    }
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<TryProperty> getTryProps()
  {
    if (tryProps == null)
    {
      tryProps = new EObjectContainmentEList<TryProperty>(TryProperty.class, this, FlowServicePackage.TRY_STEP__TRY_PROPS);
    }
    return tryProps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Step> getSteps()
  {
    if (steps == null)
    {
      steps = new EObjectContainmentEList<Step>(Step.class, this, FlowServicePackage.TRY_STEP__STEPS);
    }
    return steps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CatchStep> getCatches()
  {
    if (catches == null)
    {
      catches = new EObjectContainmentEList<CatchStep>(CatchStep.class, this, FlowServicePackage.TRY_STEP__CATCHES);
    }
    return catches;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FinallyStep getFinallyBlock()
  {
    return finallyBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFinallyBlock(FinallyStep newFinallyBlock, NotificationChain msgs)
  {
    FinallyStep oldFinallyBlock = finallyBlock;
    finallyBlock = newFinallyBlock;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FlowServicePackage.TRY_STEP__FINALLY_BLOCK, oldFinallyBlock, newFinallyBlock);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFinallyBlock(FinallyStep newFinallyBlock)
  {
    if (newFinallyBlock != finallyBlock)
    {
      NotificationChain msgs = null;
      if (finallyBlock != null)
        msgs = ((InternalEObject)finallyBlock).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FlowServicePackage.TRY_STEP__FINALLY_BLOCK, null, msgs);
      if (newFinallyBlock != null)
        msgs = ((InternalEObject)newFinallyBlock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FlowServicePackage.TRY_STEP__FINALLY_BLOCK, null, msgs);
      msgs = basicSetFinallyBlock(newFinallyBlock, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FlowServicePackage.TRY_STEP__FINALLY_BLOCK, newFinallyBlock, newFinallyBlock));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FlowServicePackage.TRY_STEP__PROPERTIES:
        return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
      case FlowServicePackage.TRY_STEP__TRY_PROPS:
        return ((InternalEList<?>)getTryProps()).basicRemove(otherEnd, msgs);
      case FlowServicePackage.TRY_STEP__STEPS:
        return ((InternalEList<?>)getSteps()).basicRemove(otherEnd, msgs);
      case FlowServicePackage.TRY_STEP__CATCHES:
        return ((InternalEList<?>)getCatches()).basicRemove(otherEnd, msgs);
      case FlowServicePackage.TRY_STEP__FINALLY_BLOCK:
        return basicSetFinallyBlock(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlowServicePackage.TRY_STEP__PROPERTIES:
        return getProperties();
      case FlowServicePackage.TRY_STEP__TRY_PROPS:
        return getTryProps();
      case FlowServicePackage.TRY_STEP__STEPS:
        return getSteps();
      case FlowServicePackage.TRY_STEP__CATCHES:
        return getCatches();
      case FlowServicePackage.TRY_STEP__FINALLY_BLOCK:
        return getFinallyBlock();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlowServicePackage.TRY_STEP__PROPERTIES:
        getProperties().clear();
        getProperties().addAll((Collection<? extends StepProperty>)newValue);
        return;
      case FlowServicePackage.TRY_STEP__TRY_PROPS:
        getTryProps().clear();
        getTryProps().addAll((Collection<? extends TryProperty>)newValue);
        return;
      case FlowServicePackage.TRY_STEP__STEPS:
        getSteps().clear();
        getSteps().addAll((Collection<? extends Step>)newValue);
        return;
      case FlowServicePackage.TRY_STEP__CATCHES:
        getCatches().clear();
        getCatches().addAll((Collection<? extends CatchStep>)newValue);
        return;
      case FlowServicePackage.TRY_STEP__FINALLY_BLOCK:
        setFinallyBlock((FinallyStep)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.TRY_STEP__PROPERTIES:
        getProperties().clear();
        return;
      case FlowServicePackage.TRY_STEP__TRY_PROPS:
        getTryProps().clear();
        return;
      case FlowServicePackage.TRY_STEP__STEPS:
        getSteps().clear();
        return;
      case FlowServicePackage.TRY_STEP__CATCHES:
        getCatches().clear();
        return;
      case FlowServicePackage.TRY_STEP__FINALLY_BLOCK:
        setFinallyBlock((FinallyStep)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlowServicePackage.TRY_STEP__PROPERTIES:
        return properties != null && !properties.isEmpty();
      case FlowServicePackage.TRY_STEP__TRY_PROPS:
        return tryProps != null && !tryProps.isEmpty();
      case FlowServicePackage.TRY_STEP__STEPS:
        return steps != null && !steps.isEmpty();
      case FlowServicePackage.TRY_STEP__CATCHES:
        return catches != null && !catches.isEmpty();
      case FlowServicePackage.TRY_STEP__FINALLY_BLOCK:
        return finallyBlock != null;
    }
    return super.eIsSet(featureID);
  }

} //TryStepImpl
