/**
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.flowService.impl;

import com.webmethods.flow.flowService.FlowServicePackage;
import com.webmethods.flow.flowService.ValidateOutput;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Validate Output</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ValidateOutputImpl extends InvokePropertyImpl implements ValidateOutput
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValidateOutputImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlowServicePackage.Literals.VALIDATE_OUTPUT;
  }

} //ValidateOutputImpl
