/*
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.webmethods.flow.ide.contentassist.antlr.internal.InternalFlowServiceParser;
import com.webmethods.flow.services.FlowServiceGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class FlowServiceParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(FlowServiceGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, FlowServiceGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStepAccess().getAlternatives(), "rule__Step__Alternatives");
			builder.put(grammarAccess.getStepPropertyAccess().getAlternatives(), "rule__StepProperty__Alternatives");
			builder.put(grammarAccess.getMapElementAccess().getAlternatives(), "rule__MapElement__Alternatives");
			builder.put(grammarAccess.getMappingBlockAccess().getAlternatives(), "rule__MappingBlock__Alternatives");
			builder.put(grammarAccess.getMappingEntryAccess().getAlternatives(), "rule__MappingEntry__Alternatives");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getInvokePropertyAccess().getAlternatives(), "rule__InvokeProperty__Alternatives");
			builder.put(grammarAccess.getLoopPropertyAccess().getAlternatives(), "rule__LoopProperty__Alternatives");
			builder.put(grammarAccess.getTryStepAccess().getAlternatives_2(), "rule__TryStep__Alternatives_2");
			builder.put(grammarAccess.getCatchPropertyAccess().getAlternatives(), "rule__CatchProperty__Alternatives");
			builder.put(grammarAccess.getBranchPropertyAccess().getAlternatives(), "rule__BranchProperty__Alternatives");
			builder.put(grammarAccess.getRepeatPropertyAccess().getAlternatives(), "rule__RepeatProperty__Alternatives");
			builder.put(grammarAccess.getExitPropertyAccess().getAlternatives(), "rule__ExitProperty__Alternatives");
			builder.put(grammarAccess.getFlowServiceAccess().getGroup(), "rule__FlowService__Group__0");
			builder.put(grammarAccess.getCommentPropertyAccess().getGroup(), "rule__CommentProperty__Group__0");
			builder.put(grammarAccess.getScopePropertyAccess().getGroup(), "rule__ScopeProperty__Group__0");
			builder.put(grammarAccess.getTimeoutPropertyAccess().getGroup(), "rule__TimeoutProperty__Group__0");
			builder.put(grammarAccess.getLabelPropertyAccess().getGroup(), "rule__LabelProperty__Group__0");
			builder.put(grammarAccess.getQualifiedServiceNameAccess().getGroup(), "rule__QualifiedServiceName__Group__0");
			builder.put(grammarAccess.getQualifiedServiceNameAccess().getGroup_1(), "rule__QualifiedServiceName__Group_1__0");
			builder.put(grammarAccess.getMapStepAccess().getGroup(), "rule__MapStep__Group__0");
			builder.put(grammarAccess.getMapStepAccess().getGroup_1(), "rule__MapStep__Group_1__0");
			builder.put(grammarAccess.getTransformStepAccess().getGroup(), "rule__TransformStep__Group__0");
			builder.put(grammarAccess.getTransformStepAccess().getGroup_2(), "rule__TransformStep__Group_2__0");
			builder.put(grammarAccess.getDropStepAccess().getGroup(), "rule__DropStep__Group__0");
			builder.put(grammarAccess.getDropStepAccess().getGroup_2(), "rule__DropStep__Group_2__0");
			builder.put(grammarAccess.getInvokeStepAccess().getGroup(), "rule__InvokeStep__Group__0");
			builder.put(grammarAccess.getInvokeStepAccess().getGroup_2(), "rule__InvokeStep__Group_2__0");
			builder.put(grammarAccess.getMappingBlockAccess().getGroup_0(), "rule__MappingBlock__Group_0__0");
			builder.put(grammarAccess.getMappingBlockAccess().getGroup_1(), "rule__MappingBlock__Group_1__0");
			builder.put(grammarAccess.getMappingCopyEntryAccess().getGroup(), "rule__MappingCopyEntry__Group__0");
			builder.put(grammarAccess.getMappingCopyEntryAccess().getGroup_2(), "rule__MappingCopyEntry__Group_2__0");
			builder.put(grammarAccess.getMappingCopyEntryAccess().getGroup_5(), "rule__MappingCopyEntry__Group_5__0");
			builder.put(grammarAccess.getMappingSetEntryAccess().getGroup(), "rule__MappingSetEntry__Group__0");
			builder.put(grammarAccess.getMappingSetEntryAccess().getGroup_2(), "rule__MappingSetEntry__Group_2__0");
			builder.put(grammarAccess.getValidateInputAccess().getGroup(), "rule__ValidateInput__Group__0");
			builder.put(grammarAccess.getValidateOutputAccess().getGroup(), "rule__ValidateOutput__Group__0");
			builder.put(grammarAccess.getLoopStepAccess().getGroup(), "rule__LoopStep__Group__0");
			builder.put(grammarAccess.getLoopStepAccess().getGroup_1(), "rule__LoopStep__Group_1__0");
			builder.put(grammarAccess.getLoopPropertyAccess().getGroup_0(), "rule__LoopProperty__Group_0__0");
			builder.put(grammarAccess.getLoopPropertyAccess().getGroup_1(), "rule__LoopProperty__Group_1__0");
			builder.put(grammarAccess.getSequenceStepAccess().getGroup(), "rule__SequenceStep__Group__0");
			builder.put(grammarAccess.getSequenceStepAccess().getGroup_1(), "rule__SequenceStep__Group_1__0");
			builder.put(grammarAccess.getSequencePropertyAccess().getGroup(), "rule__SequenceProperty__Group__0");
			builder.put(grammarAccess.getTryStepAccess().getGroup(), "rule__TryStep__Group__0");
			builder.put(grammarAccess.getTryPropertyAccess().getGroup(), "rule__TryProperty__Group__0");
			builder.put(grammarAccess.getCatchStepAccess().getGroup(), "rule__CatchStep__Group__0");
			builder.put(grammarAccess.getCatchStepAccess().getGroup_1(), "rule__CatchStep__Group_1__0");
			builder.put(grammarAccess.getCatchPropertyAccess().getGroup_0(), "rule__CatchProperty__Group_0__0");
			builder.put(grammarAccess.getCatchPropertyAccess().getGroup_1(), "rule__CatchProperty__Group_1__0");
			builder.put(grammarAccess.getCatchPropertyAccess().getGroup_2(), "rule__CatchProperty__Group_2__0");
			builder.put(grammarAccess.getFinallyStepAccess().getGroup(), "rule__FinallyStep__Group__0");
			builder.put(grammarAccess.getFinallyStepAccess().getGroup_1(), "rule__FinallyStep__Group_1__0");
			builder.put(grammarAccess.getFinallyPropertyAccess().getGroup(), "rule__FinallyProperty__Group__0");
			builder.put(grammarAccess.getBranchStepAccess().getGroup(), "rule__BranchStep__Group__0");
			builder.put(grammarAccess.getBranchStepAccess().getGroup_1(), "rule__BranchStep__Group_1__0");
			builder.put(grammarAccess.getBranchPropertyAccess().getGroup_0(), "rule__BranchProperty__Group_0__0");
			builder.put(grammarAccess.getBranchPropertyAccess().getGroup_1(), "rule__BranchProperty__Group_1__0");
			builder.put(grammarAccess.getRepeatStepAccess().getGroup(), "rule__RepeatStep__Group__0");
			builder.put(grammarAccess.getRepeatStepAccess().getGroup_1(), "rule__RepeatStep__Group_1__0");
			builder.put(grammarAccess.getRepeatPropertyAccess().getGroup_0(), "rule__RepeatProperty__Group_0__0");
			builder.put(grammarAccess.getRepeatPropertyAccess().getGroup_1(), "rule__RepeatProperty__Group_1__0");
			builder.put(grammarAccess.getRepeatPropertyAccess().getGroup_2(), "rule__RepeatProperty__Group_2__0");
			builder.put(grammarAccess.getExitStepAccess().getGroup(), "rule__ExitStep__Group__0");
			builder.put(grammarAccess.getExitStepAccess().getGroup_1(), "rule__ExitStep__Group_1__0");
			builder.put(grammarAccess.getExitPropertyAccess().getGroup_0(), "rule__ExitProperty__Group_0__0");
			builder.put(grammarAccess.getExitPropertyAccess().getGroup_1(), "rule__ExitProperty__Group_1__0");
			builder.put(grammarAccess.getExitPropertyAccess().getGroup_2(), "rule__ExitProperty__Group_2__0");
			builder.put(grammarAccess.getExitPropertyAccess().getGroup_3(), "rule__ExitProperty__Group_3__0");
			builder.put(grammarAccess.getExitPropertyAccess().getGroup_4(), "rule__ExitProperty__Group_4__0");
			builder.put(grammarAccess.getExitPropertyAccess().getGroup_5(), "rule__ExitProperty__Group_5__0");
			builder.put(grammarAccess.getExitPropertyAccess().getGroup_6(), "rule__ExitProperty__Group_6__0");
			builder.put(grammarAccess.getModelAccess().getServicesAssignment(), "rule__Model__ServicesAssignment");
			builder.put(grammarAccess.getFlowServiceAccess().getNameAssignment_1(), "rule__FlowService__NameAssignment_1");
			builder.put(grammarAccess.getFlowServiceAccess().getStepsAssignment_3(), "rule__FlowService__StepsAssignment_3");
			builder.put(grammarAccess.getCommentPropertyAccess().getValueAssignment_2(), "rule__CommentProperty__ValueAssignment_2");
			builder.put(grammarAccess.getScopePropertyAccess().getValueAssignment_2(), "rule__ScopeProperty__ValueAssignment_2");
			builder.put(grammarAccess.getTimeoutPropertyAccess().getValueAssignment_2(), "rule__TimeoutProperty__ValueAssignment_2");
			builder.put(grammarAccess.getLabelPropertyAccess().getValueAssignment_2(), "rule__LabelProperty__ValueAssignment_2");
			builder.put(grammarAccess.getQualifiedServiceNameAccess().getNamespaceAssignment_0(), "rule__QualifiedServiceName__NamespaceAssignment_0");
			builder.put(grammarAccess.getQualifiedServiceNameAccess().getNamespaceAssignment_1_1(), "rule__QualifiedServiceName__NamespaceAssignment_1_1");
			builder.put(grammarAccess.getQualifiedServiceNameAccess().getNameAssignment_3(), "rule__QualifiedServiceName__NameAssignment_3");
			builder.put(grammarAccess.getMapStepAccess().getMapElementsAssignment_1_1(), "rule__MapStep__MapElementsAssignment_1_1");
			builder.put(grammarAccess.getTransformStepAccess().getServiceAssignment_1(), "rule__TransformStep__ServiceAssignment_1");
			builder.put(grammarAccess.getTransformStepAccess().getMappingsAssignment_2_1(), "rule__TransformStep__MappingsAssignment_2_1");
			builder.put(grammarAccess.getDropStepAccess().getPathAssignment_1(), "rule__DropStep__PathAssignment_1");
			builder.put(grammarAccess.getDropStepAccess().getPathAssignment_2_1(), "rule__DropStep__PathAssignment_2_1");
			builder.put(grammarAccess.getInvokeStepAccess().getServiceAssignment_1(), "rule__InvokeStep__ServiceAssignment_1");
			builder.put(grammarAccess.getInvokeStepAccess().getPropertiesAssignment_2_1(), "rule__InvokeStep__PropertiesAssignment_2_1");
			builder.put(grammarAccess.getInvokeStepAccess().getInvokePropsAssignment_2_2(), "rule__InvokeStep__InvokePropsAssignment_2_2");
			builder.put(grammarAccess.getInvokeStepAccess().getMappingsAssignment_2_3(), "rule__InvokeStep__MappingsAssignment_2_3");
			builder.put(grammarAccess.getMappingBlockAccess().getEntriesAssignment_0_2(), "rule__MappingBlock__EntriesAssignment_0_2");
			builder.put(grammarAccess.getMappingBlockAccess().getEntriesAssignment_1_2(), "rule__MappingBlock__EntriesAssignment_1_2");
			builder.put(grammarAccess.getMappingCopyEntryAccess().getFromPathAssignment_1(), "rule__MappingCopyEntry__FromPathAssignment_1");
			builder.put(grammarAccess.getMappingCopyEntryAccess().getFromPathAssignment_2_1(), "rule__MappingCopyEntry__FromPathAssignment_2_1");
			builder.put(grammarAccess.getMappingCopyEntryAccess().getToPathAssignment_4(), "rule__MappingCopyEntry__ToPathAssignment_4");
			builder.put(grammarAccess.getMappingCopyEntryAccess().getToPathAssignment_5_1(), "rule__MappingCopyEntry__ToPathAssignment_5_1");
			builder.put(grammarAccess.getMappingSetEntryAccess().getPathAssignment_1(), "rule__MappingSetEntry__PathAssignment_1");
			builder.put(grammarAccess.getMappingSetEntryAccess().getPathAssignment_2_1(), "rule__MappingSetEntry__PathAssignment_2_1");
			builder.put(grammarAccess.getMappingSetEntryAccess().getValueAssignment_4(), "rule__MappingSetEntry__ValueAssignment_4");
			builder.put(grammarAccess.getValidateInputAccess().getValueAssignment_2(), "rule__ValidateInput__ValueAssignment_2");
			builder.put(grammarAccess.getValidateOutputAccess().getValueAssignment_2(), "rule__ValidateOutput__ValueAssignment_2");
			builder.put(grammarAccess.getLoopStepAccess().getPropertiesAssignment_1_1(), "rule__LoopStep__PropertiesAssignment_1_1");
			builder.put(grammarAccess.getLoopStepAccess().getLoopPropsAssignment_1_2(), "rule__LoopStep__LoopPropsAssignment_1_2");
			builder.put(grammarAccess.getLoopStepAccess().getStepsAssignment_1_3(), "rule__LoopStep__StepsAssignment_1_3");
			builder.put(grammarAccess.getLoopPropertyAccess().getInputAssignment_0_2(), "rule__LoopProperty__InputAssignment_0_2");
			builder.put(grammarAccess.getLoopPropertyAccess().getOutputAssignment_1_2(), "rule__LoopProperty__OutputAssignment_1_2");
			builder.put(grammarAccess.getSequenceStepAccess().getPropertiesAssignment_1_1(), "rule__SequenceStep__PropertiesAssignment_1_1");
			builder.put(grammarAccess.getSequenceStepAccess().getSeqPropsAssignment_1_2(), "rule__SequenceStep__SeqPropsAssignment_1_2");
			builder.put(grammarAccess.getSequenceStepAccess().getStepsAssignment_1_3(), "rule__SequenceStep__StepsAssignment_1_3");
			builder.put(grammarAccess.getSequencePropertyAccess().getValueAssignment_2(), "rule__SequenceProperty__ValueAssignment_2");
			builder.put(grammarAccess.getTryStepAccess().getPropertiesAssignment_2_0(), "rule__TryStep__PropertiesAssignment_2_0");
			builder.put(grammarAccess.getTryStepAccess().getTryPropsAssignment_2_1(), "rule__TryStep__TryPropsAssignment_2_1");
			builder.put(grammarAccess.getTryStepAccess().getStepsAssignment_3(), "rule__TryStep__StepsAssignment_3");
			builder.put(grammarAccess.getTryStepAccess().getCatchesAssignment_5(), "rule__TryStep__CatchesAssignment_5");
			builder.put(grammarAccess.getTryStepAccess().getFinallyBlockAssignment_6(), "rule__TryStep__FinallyBlockAssignment_6");
			builder.put(grammarAccess.getTryPropertyAccess().getValueAssignment_2(), "rule__TryProperty__ValueAssignment_2");
			builder.put(grammarAccess.getCatchStepAccess().getPropertiesAssignment_1_1(), "rule__CatchStep__PropertiesAssignment_1_1");
			builder.put(grammarAccess.getCatchStepAccess().getCatchPropsAssignment_1_2(), "rule__CatchStep__CatchPropsAssignment_1_2");
			builder.put(grammarAccess.getCatchStepAccess().getStepsAssignment_1_3(), "rule__CatchStep__StepsAssignment_1_3");
			builder.put(grammarAccess.getCatchPropertyAccess().getExitAssignment_0_2(), "rule__CatchProperty__ExitAssignment_0_2");
			builder.put(grammarAccess.getCatchPropertyAccess().getFailuresAssignment_1_2(), "rule__CatchProperty__FailuresAssignment_1_2");
			builder.put(grammarAccess.getCatchPropertyAccess().getSelectionAssignment_2_2(), "rule__CatchProperty__SelectionAssignment_2_2");
			builder.put(grammarAccess.getFinallyStepAccess().getPropertiesAssignment_1_1(), "rule__FinallyStep__PropertiesAssignment_1_1");
			builder.put(grammarAccess.getFinallyStepAccess().getFinalPropsAssignment_1_2(), "rule__FinallyStep__FinalPropsAssignment_1_2");
			builder.put(grammarAccess.getFinallyStepAccess().getStepsAssignment_1_3(), "rule__FinallyStep__StepsAssignment_1_3");
			builder.put(grammarAccess.getFinallyPropertyAccess().getValueAssignment_2(), "rule__FinallyProperty__ValueAssignment_2");
			builder.put(grammarAccess.getBranchStepAccess().getPropertiesAssignment_1_1(), "rule__BranchStep__PropertiesAssignment_1_1");
			builder.put(grammarAccess.getBranchStepAccess().getBranchPropsAssignment_1_2(), "rule__BranchStep__BranchPropsAssignment_1_2");
			builder.put(grammarAccess.getBranchStepAccess().getStepsAssignment_1_3(), "rule__BranchStep__StepsAssignment_1_3");
			builder.put(grammarAccess.getBranchPropertyAccess().getSwitchAssignment_0_2(), "rule__BranchProperty__SwitchAssignment_0_2");
			builder.put(grammarAccess.getBranchPropertyAccess().getEvalAssignment_1_2(), "rule__BranchProperty__EvalAssignment_1_2");
			builder.put(grammarAccess.getRepeatStepAccess().getPropertiesAssignment_1_1(), "rule__RepeatStep__PropertiesAssignment_1_1");
			builder.put(grammarAccess.getRepeatStepAccess().getRepeatPropsAssignment_1_2(), "rule__RepeatStep__RepeatPropsAssignment_1_2");
			builder.put(grammarAccess.getRepeatStepAccess().getStepsAssignment_1_3(), "rule__RepeatStep__StepsAssignment_1_3");
			builder.put(grammarAccess.getRepeatPropertyAccess().getCountAssignment_0_2(), "rule__RepeatProperty__CountAssignment_0_2");
			builder.put(grammarAccess.getRepeatPropertyAccess().getIntervalAssignment_1_2(), "rule__RepeatProperty__IntervalAssignment_1_2");
			builder.put(grammarAccess.getRepeatPropertyAccess().getOnAssignment_2_2(), "rule__RepeatProperty__OnAssignment_2_2");
			builder.put(grammarAccess.getExitStepAccess().getExitPropsAssignment_1_1(), "rule__ExitStep__ExitPropsAssignment_1_1");
			builder.put(grammarAccess.getExitPropertyAccess().getCommentAssignment_0_2(), "rule__ExitProperty__CommentAssignment_0_2");
			builder.put(grammarAccess.getExitPropertyAccess().getLabelAssignment_1_2(), "rule__ExitProperty__LabelAssignment_1_2");
			builder.put(grammarAccess.getExitPropertyAccess().getSignalAssignment_2_2(), "rule__ExitProperty__SignalAssignment_2_2");
			builder.put(grammarAccess.getExitPropertyAccess().getFailureNameAssignment_3_2(), "rule__ExitProperty__FailureNameAssignment_3_2");
			builder.put(grammarAccess.getExitPropertyAccess().getFailureInstanceAssignment_4_2(), "rule__ExitProperty__FailureInstanceAssignment_4_2");
			builder.put(grammarAccess.getExitPropertyAccess().getExitFormAssignment_5_2(), "rule__ExitProperty__ExitFormAssignment_5_2");
			builder.put(grammarAccess.getExitPropertyAccess().getFailureMessageAssignment_6_2(), "rule__ExitProperty__FailureMessageAssignment_6_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private FlowServiceGrammarAccess grammarAccess;

	@Override
	protected InternalFlowServiceParser createParser() {
		InternalFlowServiceParser result = new InternalFlowServiceParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public FlowServiceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FlowServiceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
