/*
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFlowServiceScopeProvider extends DelegatingScopeProvider {
}
