/*
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.ide;


/**
 * Use this class to register ide components.
 */
public class FlowServiceIdeModule extends AbstractFlowServiceIdeModule {
}
