/*
 * generated by Xtext 2.38.0
 */
package com.webmethods.flow.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.webmethods.flow.FlowServiceRuntimeModule;
import com.webmethods.flow.FlowServiceStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FlowServiceIdeSetup extends FlowServiceStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FlowServiceRuntimeModule(), new FlowServiceIdeModule()));
	}
	
}
